'use strict';
const assert=require('node:assert/strict');
const E=require('../src/engine.js');const D=require('../src/data.js');
let pass=0;const test=(name,fn)=>{try{fn();console.log('PASS '+name);pass++;}catch(e){console.error('FAIL '+name);throw e;}};
const near=(x,y,t=1e-8)=>assert.ok(Math.abs(x-y)<=t,`${x} != ${y}`);
function minimal(){let s=D.state(true);s.meta.demo=false;s.base={oa:3000};s.target={da:3000,daReduction:0,resistMode:'final',resists:{},rr:[],armor:0,armorAbsorption:100,absorption:0,flatAbsorption:0,avoidance:0};s.combat={dual:false,darWD:100,darFlat:{},skillConversion:{},totalDamageModifier:0,basicCycleMs:1000,referenceSpeed:100,speedCap:200,timingMode:'cycles',measuredAPS:1,uptime:100};s.wps=[];s.extras=[];s.buffs=[];s.equipment=D.state(false).equipment;for(const e of Object.values(s.equipment)){e.parts=Object.fromEntries(D.PARTS.map(([k])=>[k,D.blankPart()]));e.reviewed=true;}s.equipment.main.parts.item={name:'Test',stats:{flat_pierce:100},enabled:true};return s;}

test('OA == DA gives PTH 90',()=>near(E.pth(3000,3000),90));
test('PTH minimum is 55',()=>near(E.pth(1,100000),55));
test('hit/crit probabilities always sum to 1',()=>{for(let oa=1;oa<20000;oa+=53){const r=E.critProfile(oa,3000,50);near(r.bins.reduce((s,b)=>s+b.p,0),1);assert.ok(r.crit>=0&&r.crit<=1);}});
test('below 70 reduced normal damage',()=>{const r=E.critProfile(1,100000,0);near(r.mean,.55*(55/70));});
test('OA 3400/DA3000 expected critical probability',()=>near(E.critProfile(3400,3000,50).crit,0.10872729447889459));
test('flat elemental split into thirds',()=>{const v=E.flat({flat_elemental:30});near(v.fire,10);near(v.cold,10);near(v.lightning,10);});
test('local conversion then unconverted remainder only',()=>{const v=E.convert({cold:100},{conv_cold:50},{conv_cold:50});near(v.pierce,75);near(v.cold,25);});
test('full local conversion cannot double convert',()=>{const v=E.convert({cold:100},{conv_cold:100},{conv_cold:100});near(v.pierce,100);});
test('Armor Piercing converts remaining physical once',()=>{const v=E.convert({physical:100},{conv_physical:50},{},50);near(v.pierce,75);near(v.physical,25);});
test('empty WPS pool leaves 100% ordinary',()=>near(E.pool([]).basic,1));
test('WPS 150% is normalized to 100%',()=>{const p=E.pool([{chance:75},{chance:75}]);near(p.rows[0].p,.5);near(p.basic,0);});
test('disabled WPS does not dilute pool',()=>{const p=E.pool([{chance:75},{chance:75,enabled:false}]);near(p.rows[0].p,.75);near(p.basic,.25);});
test('simple baseline deals 90 DPS after 90% hit chance',()=>near(E.calculate(minimal()).total,90));
test('DAR and WPS damage coefficients multiply; flats add',()=>{const s=minimal();s.combat.darWD=200;s.combat.darFlat={flat_pierce:10};s.wps=[{id:'a',chance:100,wd:50,hitsMain:1,hitsOff:0,cycleMs:1000,flat:{flat_pierce:20}}];near(E.calculate(s).total,117);});
test('main and offhand local flat damage are not double counted',()=>{const s=minimal();s.equipment.off.parts.item.stats={flat_pierce:500};near(E.calculate(s).total,90);});
test('non-weapon flat damage applies globally',()=>{const s=minimal();s.equipment.ring1.parts.item.stats={flat_pierce:20};near(E.calculate(s).total,108);});
test('global % bonuses on offhand also apply to mainhand',()=>{const s=minimal();s.equipment.off.parts.item.stats={inc_pierce:100};near(E.calculate(s).total,180);});
test('normal dual basic average uses 1.5 hands',()=>{const s=minimal();s.combat.dual=true;s.equipment.off.parts.item.stats={flat_pierce:100};near(E.calculate(s).total,135);});
test('weighted time is denominator, not average of per-skill DPS',()=>{const s=minimal();s.wps=[{id:'a',chance:50,wd:100,hitsMain:1,cycleMs:1000},{id:'b',chance:50,wd:100,hitsMain:1,cycleMs:3000}];near(E.calculate(s).total,45);});
test('attack speed cap',()=>{const s=minimal();s.base.attackSpeed=100;const a=E.calculate(s).total;s.base.attackSpeed=200;near(E.calculate(s).total,a);});
test('measured rate ignores attack speed changes',()=>{const s=minimal();s.combat.timingMode='measured';s.base.attackSpeed=100;near(E.calculate(s).total,90);});
test('uptime scales direct damage only',()=>{const s=minimal();s.combat.uptime=50;near(E.calculate(s).total,45);});
test('final zero resistance differs from -100 by factor two',()=>{const s=minimal();s.target.resists.pierce=-100;near(E.calculate(s).total,180);});
test('100% resistance yields zero for that type',()=>{const s=minimal();s.target.resists.pierce=100;near(E.calculate(s).total,0);});
test('physical armor applied to each packet',()=>{const s=minimal();s.equipment.main.parts.item.stats={flat_physical:120};s.target.armor=100;near(E.calculate(s).total,18);});
test('flat absorption follows armor and percentage absorption',()=>{const s=minimal();s.equipment.main.parts.item.stats={flat_physical:200};s.target.armor=50;s.target.absorption=50;s.target.flatAbsorption=25;near(E.calculate(s).total,45);});
test('avoidance multiplies landed damage',()=>{const s=minimal();s.target.avoidance=20;near(E.calculate(s).total,72);});
test('same RR ID is not stacked; flat RR uses highest',()=>{const t={resistMode:'base',resists:{pierce:80},rr:[{type:'pierce',kind:'stack',group:'a',value:20},{type:'pierce',kind:'stack',group:'a',value:25},{type:'pierce',kind:'stack',group:'b',value:30},{type:'all',kind:'flat',value:28},{type:'all',kind:'flat',value:20}]};near(E.rrValue(t,'pierce'),-3);});
test('final resistance mode bypasses RR list',()=>{const t={resistMode:'final',resists:{pierce:80},rr:[{type:'pierce',kind:'stack',value:20}]};near(E.rrValue(t,'pierce'),80);});
test('same dot source keeps max; distinct sources add',()=>{const s=minimal();s.extras=[{id:'1',kind:'dot',type:'bleed',group:'a',rate:100,uptime:100,afterMitigation:true},{id:'2',kind:'dot',type:'bleed',group:'a',rate:200,uptime:100,afterMitigation:true},{id:'3',kind:'dot',type:'bleed',group:'b',rate:50,uptime:100,afterMitigation:true}];near(E.calculate(s).extra,250);s.base.attackSpeed=100;near(E.calculate(s).extra,250);});
test('ascension proc chance from equipment affects pool',()=>{const s=minimal();s.wps=[{id:'storm',chance:20,wd:100,hitsMain:1,cycleMs:1000}];s.equipment.head.parts.ascension.stats={chance_storm:10};near(E.calculate(s).pool.sum,30);});
test('seeded simulation is reproducible',()=>{const s=D.state(true);assert.deepEqual(E.simulate(s,10,7).events,E.simulate(s,10,7).events);});
test('long simulated averages approach expectation',()=>{const s=D.state(true);const a=E.calculate(s).total;let sum=0;for(let i=1;i<=16;i++)sum+=E.simulate(s,120,i).events.reduce((v,e)=>v+e.damage,0)/120;assert.ok(Math.abs(sum/16/a-1)<.035);});
test('trace total includes silent time in denominator',()=>{const a=E.analyzeEvents([{time:1,damage:100},{time:2,damage:100}],{start:0,end:10});near(a.average,20);});
test('rolling window drops exact left boundary',()=>{const a=E.analyzeEvents([{time:0,damage:100},{time:5,damage:200}],{start:0,end:5,window:5,step:1});near(a.points.at(-1).dps,40);near(a.total,300);});
test('full-window peak at event times, not sampled grid',()=>{const a=E.analyzeEvents([{time:5.1234,damage:500}],{start:0,end:10,window:5,step:1});near(a.peak,100);});
test('short trace does not claim full-window peak',()=>assert.equal(E.analyzeEvents([{time:1,damage:100}],{end:2}).peak,null));
test('long trace has bounded chart point count',()=>assert.ok(E.analyzeEvents([{time:1,damage:1}],{end:10000000}).points.length<=2001));
test('invalid duration is rejected',()=>assert.throws(()=>E.analyzeEvents([],{start:2,end:1})));
test('nested timestamp milliseconds map explicitly',()=>{const a=E.mapEvents([{event:{timeMs:1000,damage:50}},{event:{timeMs:2000,damage:70}}],{time:'event.timeMs',damage:'event.damage',unit:'ms',relative:true});near(a.events[0].time,0);near(a.events[1].time,1);});
test('timestamp zero is valid, missing timestamp is not invented',()=>{const r=E.mapEvents([{t:0,d:10},{d:20}],{time:'t',damage:'d',unit:'s'});near(r.events[0].damage,10);near(r.skipped,1);});
test('no timing information is rejected',()=>assert.throws(()=>E.mapEvents([{damage:200}],{time:'time',damage:'damage'})));
test('CSV quoting and embedded commas',()=>{const r=E.parseCSV('time,damage,skill\n0,12,"a,b"\n1,13,"x""y"');assert.equal(r[0].skill,'a,b');assert.equal(r[1].skill,'x"y');});
test('CSV unclosed quote is rejected',()=>assert.throws(()=>E.parseCSV('x,y\n"foo,1')));
test('tooltip supported fields',()=>{const r=E.parseTooltip('10 Piercing Damage\n+50% Piercing Damage\n70 Defensive Ability');near(r.stats.flat_pierce,10);near(r.stats.inc_pierce,50);near(r.stats.da,70);});
test('tooltip ranges become averages and regeneration is not health',()=>{const r=E.parseTooltip('10-20 Piercing Damage\n12 Health Regeneration');near(r.stats.flat_pierce,15);assert.equal(r.stats.hp,undefined);near(r.unknown.length,1);});
test('tooltip Korean supported fields',()=>{const r=E.parseTooltip('관통 피해 +50%\n공격 능력 +70\n+20% 공격 속도');near(r.stats.inc_pierce,50);near(r.stats.oa,70);near(r.stats.attackSpeed,20);});
test('template does not silently install fabricated weapon stats',()=>{const s=D.state(false);assert.deepEqual(s.equipment.main.parts.item.stats,{});assert.equal(s.meta.demo,false);});
console.log(`\n${pass} engine tests passed.`);
