/* Local item database UI. User builds and logs never leave this browser. */
(function(){
'use strict';
const {SLOTS,PARTS,FIELDS,FIELD_LABELS,SOURCES}=DATA;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,d=0)=>Number.isFinite(x)?x.toLocaleString('ko-KR',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const short=x=>x>=10000?fmt(x/10000,1)+'만':fmt(x);
const icon=(id,cls='svg-icon')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${{
 gem:'<path d="M12 2 21 8 18 18 12 22 6 18 3 8Z"/><path d="m3 8 9 5 9-5M12 13v9M7 5l5 8 5-8"/>',
 gear:'<path d="M7 3 3 7l3 3v10h12V10l3-3-4-4-5 3Z"/><path d="M9 6h6M9 12h6M9 15h6"/>',
 gun:'<path d="M3 6h16l2 3-2 3h-7l-2 7H5l2-8H3Z"/><path d="M12 12v3h3l1-3M5 6V4h3"/>',
 chart:'<path d="M4 3v17h17M7 15l4-5 4 2 5-7"/>',target:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="M12 1v4m0 14v4M1 12h4m14 0h4"/>',
 log:'<path d="M6 3h12v18H6zM9 7h6M9 11h6M9 15h4"/>',book:'<path d="M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3Z"/><path d="M12 6v16"/>',
 upload:'<path d="M12 16V3m-4 4 4-4 4 4M4 15v6h16v-6"/>',download:'<path d="M12 3v13m-4-4 4 4 4-4M4 17v4h16v-4"/>',save:'<path d="M4 3h13l4 4v14H3V3h1Z"/><path d="M7 3v6h10V3M7 21v-8h10v8"/>',
 compare:'<path d="M3 7h16l-4-4M21 17H5l4 4M7 10v5m10-5v5"/>',plus:'<path d="M12 5v14M5 12h14"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>',
 bolt:'<path d="m14 2-10 12h7l-1 8L20 9h-7Z"/>',ring:'<circle cx="12" cy="14" r="7"/><path d="m8 5 4-3 4 3-4 4Z"/>',helmet:'<path d="M4 15V9a8 8 0 0 1 16 0v6l-5 6h-6Z"/><path d="M5 11h5v5m9-5h-5v5"/>',boots:'<path d="M7 3h10v12l4 3v3H3v-5l4-3Z"/><path d="M7 8h10M7 12h10"/>',shield:'<path d="m12 2 8 4v7c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',check:'<path d="m5 12 4 4L20 5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>'
 }[id]||'<circle cx="12" cy="12" r="7"/>'}</svg>`;
const KEY='grim-dps-lab-v3';
let state=DATA.state(false),savedA=null,customLibrary=[],tab='gear',slot='main',part='item',result=null;
state.auto=AUTO.defaults();
let logData={arrays:[],rows:[],events:[],fileName:'',map:{unit:'s',relative:true},filterSource:'all',filterTarget:'all',start:0,end:60,window:5,mitigation:'unknown',sample:false,skipped:0};
let timer=null,libraryTarget=null,tooltipPreview=null,lastFocus=null;
function loadLocal(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x?.state)state=validateState(x.state);if(x?.savedA)savedA=validateState(x.savedA);if(Array.isArray(x?.library))customLibrary=x.library.slice(0,500);}catch(e){console.warn('Saved state not restored:',e.message);}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({state,savedA,library:customLibrary}));$('#save-status')&&( $('#save-status').textContent='이 브라우저에 저장됨');}catch{ $('#save-status')&&($('#save-status').textContent='자동 저장 제한 · JSON 저장 권장');}}
function toast(msg){$('.toast')?.remove();const d=document.createElement('div');d.className='toast';d.setAttribute('role','status');d.textContent=msg;document.body.append(d);setTimeout(()=>d.remove(),4000);}
function set(path,value,obj=state){const keys=path.split('.');if(keys.some(k=>['__proto__','constructor','prototype'].includes(k)))return;let p=obj;for(const k of keys.slice(0,-1)){if(!p[k]||typeof p[k]!=='object')p[k]={};p=p[k];}p[keys.at(-1)]=value;}
function get(path,obj=state){return path.split('.').reduce((p,k)=>p?.[k],obj);}
function validateState(x){
 if(!x||x.schema!=='grim-dps-lab/v1')throw new Error('이 앱의 빌드 JSON이 아닙니다. 기존 앱의 빌드 JSON만 가져올 수 있습니다. 그림툴 링크는 아이템 검색과 별개입니다.');
 const s=GD.copy(x);if(!s.base||!s.equipment||!s.combat||!s.target||!Array.isArray(s.wps)||s.wps.length>20)throw new Error('필수 항목 또는 발동 사격 개수를 확인하세요.');
 const encoded=JSON.stringify(s);if(encoded.length>1500000)throw new Error('빌드 파일이 너무 큽니다.');
 function walk(v,depth=0){if(depth>20)throw new Error('중첩 구조가 너무 깊습니다.');if(typeof v==='number'&&(!Number.isFinite(v)||Math.abs(v)>1e10))throw new Error('숫자 범위를 확인하세요.');if(v&&typeof v==='object')for(const[k,t]of Object.entries(v)){if(['__proto__','constructor','prototype'].includes(k))throw new Error('허용되지 않는 키입니다.');walk(t,depth+1);}}
 walk(s);
 const obj=v=>v&&typeof v==='object'&&!Array.isArray(v);
 if(!obj(s.base)||!obj(s.equipment)||!obj(s.combat)||!obj(s.target))throw new Error('빌드의 기본 구조가 올바르지 않습니다.');
 for(const w of s.wps){if(!obj(w)||typeof w.id!=='string'||w.id.length>80)throw new Error('발동 사격 ID를 확인하세요.');for(const k of ['hitsMain','hitsOff'])if(GD.n(w[k])<0||GD.n(w[k])>50)throw new Error('사격당 타격 수는 0~50 범위입니다.');}
 s.meta=obj(s.meta)?s.meta:{name:'가져온 빌드',demo:false};
 if(s.buffs&&!Array.isArray(s.buffs)||s.extras&&!Array.isArray(s.extras)||s.target.rr&&!Array.isArray(s.target.rr))throw new Error('버프·추가 피해·저항 감소는 배열이어야 합니다.');
 s.buffs=(s.buffs||[]).slice(0,40);s.extras=(s.extras||[]).slice(0,100);s.target.resists=s.target.resists||{};s.target.rr=(s.target.rr||[]).slice(0,100);
 if([...s.buffs,...s.extras,...s.target.rr].some(v=>!obj(v)))throw new Error('목록에 잘못된 항목이 있습니다.');
 for(const e of Object.values(s.equipment)){if(!obj(e)||e.parts&&!obj(e.parts))throw new Error('장비 옵션 구조를 확인하세요.');for(const p of Object.values(e.parts||{}))if(!obj(p)||p.stats&&!obj(p.stats))throw new Error('장비 수치는 객체로 입력해야 합니다.');}
 
 for(const[id]of SLOTS){if(!s.equipment[id])s.equipment[id]={enabled:true,reviewed:false,parts:{}};s.equipment[id].parts=s.equipment[id].parts||{};for(const[p]of PARTS)s.equipment[id].parts[p]=s.equipment[id].parts[p]||DATA.blankPart();}
 s.duration=GD.clamp(s.duration||60,5,300);return s;
}
function field(label,path,{step=1,min,max,type='number',hint='',cls='',placeholder='',value}={}){const v=value!==undefined?value:get(path);return `<label class="field ${cls}">${esc(label)}<input type="${type}" data-bind="${esc(path)}" value="${esc(v??(type==='number'?0:''))}" ${type==='number'?`step="${step}" ${min!==undefined?`min="${min}"`:''} ${max!==undefined?`max="${max}"`:''}`:''} placeholder="${esc(placeholder)}">${hint?`<em>${esc(hint)}</em>`:''}</label>`;}
function check(label,path){return `<label class="check"><input type="checkbox" data-bind="${path}" ${get(path)?'checked':''}>${esc(label)}</label>`;}
function select(label,path,options){return `<label class="field">${esc(label)}<select data-bind="${path}">${options.map(([v,l])=>`<option value="${esc(v)}" ${get(path)===v?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;}
function statsFields(path,{all=true}={}){return FIELDS.slice(0,all?4:2).map(([group,fields],i)=>`<details ${i<2?'open':''}><summary>${group}</summary><div class="field-grid">${fields.map(([k,l])=>field(l,`${path}.${k}`,{step:.1})).join('')}</div></details>`).join('');}
function panel(title,sub,body,action=''){return `<section class="panel"><div class="panel-head"><div><h2>${title}</h2>${sub?`<div class="panel-sub">${sub}</div>`:''}</div>${action}</div><div class="panel-body">${body}</div></section>`;}
function snapshotDelta(v,k){if(!savedA)return'';const old=GD.calculate(savedA)[k];if(!old)return'';const d=(v/old-1)*100;return `<span class="delta ${d<0?'negative':''}">${d>=0?'+':''}${fmt(d,1)}% vs A</span>`;}
function header(){return `<div class="topbar"><div class="breadcrumb">워크스페이스 <span style="margin:0 8px">/</span> <b>빌드 실험실</b></div><div class="toolbar"><span id="save-status" class="tiny muted">이 브라우저에 저장됨</span><button class="btn" data-action="import-build">${icon('upload')} 불러오기</button><button class="btn" data-action="export-build">${icon('download')} JSON 저장</button><button class="btn primary" data-action="snapshot">${icon('compare')} A 기준 저장</button></div></div>
 <div class="hero"><div><div class="eyebrow">GRIM DAWN · DAMAGE WORKBENCH</div><h1>DPS 워크벤치 <span class="version-tag">3.0 · BETA</span></h1><div class="subtitle">장비를 고르고, 스킬과 별자리를 찍으면 계산이 연결됩니다.</div></div><div class="row"><span class="badge ${state.meta.demo?'':'good'}">${state.meta.demo?'작동 예제 · 가정값':(state.meta.dbImported?'DB 기반 · 부분 예측':'아이템 선택 대기')}</span><button class="btn small" data-action="template">서약운반자 DB 자동 장착</button></div></div>
 <div id="db-status">${dbStatus()}</div><div class="notice">${icon('info')}<div>${state.meta.demo?'<strong>현재는 작동 예제입니다.</strong> 검색 DB에서 실제 아이템을 장착하면 예제 장비·기초 능력치를 제거합니다.':'<strong>장비·스킬 레벨·숙련도·별자리를 자동 합산합니다.</strong> 펫 AI·특수 공격 순서·정확한 게임 타이밍은 미지원이며, 계산값은 지원 효과의 근사 소계입니다.'} DPS는 독립 예측 모델이며, 미지원 효과는 자동 합산하지 않습니다.</div></div>
 <div id="metrics" class="stats"></div>${savedA?`<div class="compare-strip">${icon('compare')} <span><strong>A: ${esc(savedA.meta.name)}</strong> · 저장 시점의 장비·대상·전투 조건 전체</span><button class="btn small" data-action="restore-a">A 복원</button><button class="btn small ghost" data-action="clear-a">비교 해제</button></div>`:''}
 <div class="tabbar" role="tablist">${[['gear','장비'],['character','캐릭터'],['skills','스킬'],['devotions','별자리'],['target','대상·회전'],['analysis','피해 분석'],['audit','검증·출처'],['logs','DPYes 로그'],['help','도움말']].map(([id,l])=>`<button role="tab" aria-selected="${tab===id}" class="${tab===id?'active':''}" data-action="tab" data-tab="${id}">${l}</button>`).join('')}</div>`;}
function render(){
 result=GD.calculate(state);
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">${icon('gem')}<div><strong>GRIM / LAB</strong><small>DAMAGE ANALYTICS</small></div></div><div class="side-label">WORKSPACE</div><nav class="nav" aria-label="주 메뉴">${[['gear','gear','장비 워크벤치'],['character','shield','캐릭터 능력치'],['skills','bolt','스킬 자동 계산'],['devotions','gem','별자리'],['analysis','chart','피해 분석'],['audit','check','검증·출처'],['logs','log','DPYes 로그'],['help','book','계산식과 출처']].map(([id,i,l])=>`<button title="${l}" class="${tab===id?'active':''}" data-action="tab" data-tab="${id}">${icon(i)}${l}</button>`).join('')}</nav><div class="side-label">BUILD TOOLS</div><nav class="nav"><button data-action="demo" title="작동 예제">${icon('target')}작동 예제</button><button data-action="edit-meta" title="빌드 정보">${icon('save')}빌드 정보</button></nav><div class="side-bottom"><strong><span class="dot"></span>LOCAL DATABASE</strong>설정과 로그는 이 기기에서만 처리됩니다.<br><br>비공식 도구 · v3.0 BETA<br>DPYes / GrimTools와 별개</div></aside><main class="main">${header()}<div class="workspace"><div id="tab-content">${state.auto?.enabled&&['character','skills','devotions','target','audit','analysis'].includes(tab)?AUTOUI.view(tab,state,result):({gear:gearView,skills:skillsView,target:targetView,analysis:analysisView,logs:logsView,help:helpView,character:()=>AUTOUI.view('character',state,result),devotions:()=>AUTOUI.view('devotions',state,result),audit:()=>AUTOUI.view('audit',state,result)}[tab])()}</div><aside class="result-aside" id="aside"></aside></div><div class="footnote">Grim Dawn 및 아이템 명칭은 Crate Entertainment의 자산입니다. 이 도구는 비공식·독립 구현이며 게임 엔진, GrimTools 또는 DPYes의 복제본이 아닙니다.</div></main></div>`;
 updateMetrics();renderAside();if(tab==='analysis'&&!state.auto?.enabled)renderAnalysisDynamic();if(tab==='logs'&&logData.events.length)renderLogAnalysis();persist();
}
function updateMetrics(){
 result=GD.calculate(state);const r=result,confidence=!state.meta.demo&&r.a.named>r.a.confirmed,needsBase=state.auto?.enabled?!r.autoReport?.ready:!state.meta.demo&&GD.n(state.base.oa)<=1;
 $('#metrics').innerHTML=`<div class="stat primary"><div class="stat-label">지원분 예상 DPS <span class="scope-pill">${state.auto?.enabled?(r.coverage?.valid?'자동 합산 · 근사':'입력 검증 필요'):state.meta.dbImported?'장비 자동 · 부분 모델':confidence?'미입력 포함 소계':'독립 모델'}</span></div><div class="stat-value">${needsBase?'—':fmt(r.total)}<span class="stat-unit">DPS</span></div><div class="stat-foot">${needsBase?'DB와 직업·주력 스킬을 선택하세요':'사격 유지율 '+fmt(r.uptime*100)+'% 반영'} ${snapshotDelta(r.total,'total')}</div></div><div class="stat"><div class="stat-label">정지 사격 · 직접 피해</div><div class="stat-value">${needsBase?'—':fmt(r.aps*r.meanDamage)}<span class="stat-unit">/ s</span></div><div class="stat-foot">지속 피해·추가 발동 제외</div></div><div class="stat"><div class="stat-label">치명타 확률</div><div class="stat-value">${needsBase?'—':fmt(r.profile.crit*100,1)}<span class="stat-unit">%</span></div><div class="stat-foot">명중 ${fmt(r.profile.hit*100,1)}% · OA ${fmt(r.a.oa)}</div></div><div class="stat"><div class="stat-label">발동 사격 합계</div><div class="stat-value">${fmt(r.pool.sum,1)}<span class="stat-unit">%</span></div><div class="stat-foot">기본 공격 비중 ${fmt(r.pool.basic*100,1)}% · ${fmt(r.aps,2)} 회/s</div></div>`;
}
function chart(points,height=135,average=null){
 if(!points?.length)return'<div class="empty">피해 기록이 없습니다.</div>';
 const w=610,h=height,L=49,R=12,T=12,B=24,mx=Math.max(1,...points.map(p=>p.dps)),mt=Math.max(1,...points.map(p=>p.time));
 const x=t=>L+t/mt*(w-L-R),y=v=>h-B-v/mx*(h-T-B);
 const path=points.map((p,i)=>`${i?'L':'M'}${x(p.time).toFixed(2)},${y(p.dps).toFixed(2)}`).join(' ');
 return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="시간에 따른 최근 구간 DPS 그래프"><defs><linearGradient id="chartGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#b9ed86" stop-opacity=".18"/><stop offset="100%" stop-color="#b9ed86" stop-opacity="0"/></linearGradient></defs>${[0,.5,1].map(q=>`<path d="M${L} ${y(mx*q)}H${w-R}" class="chart-grid"/><text x="${L-8}" y="${y(mx*q)+3}" text-anchor="end" class="chart-label">${esc(short(mx*q))}</text>`).join('')}<path class="chart-fill" d="${path} L${x(mt)},${h-B} L${x(points[0].time)},${h-B}Z"/><path d="${path}" class="chart-line"/>${average!==null?`<path d="M${L} ${y(average)}H${w-R}" stroke="#e5bc75" stroke-width="1" stroke-dasharray="5 5"/>`:''}${[0,.5,1].map(q=>`<text x="${x(mt*q)}" y="${h-5}" text-anchor="middle" class="chart-label">${fmt(mt*q)}s</text>`).join('')}</svg>`;
}
function renderAside(){
 const r=result||GD.calculate(state);const dist=r.rows.filter(x=>x.p>0).sort((a,b)=>b.dps-a.dps);
 $('#aside').innerHTML=panel('계산 상태','입력된 조건을 그대로 사용합니다.',`<div class="mini-row"><span class="muted">주무기 기초 피해¹</span><b>${fmt(Object.values(r.a.hands.main).reduce((a,b)=>a+b,0),1)}</b></div><div class="mini-row"><span class="muted">관통 피해 증가</span><b>+${fmt(GD.n(r.a.g.inc_pierce)+GD.n(r.a.g.incAll),1)}%</b></div><div class="mini-row"><span class="muted">유효 공격 속도</span><b>${fmt(r.a.speed,1)}%</b></div><div class="mini-row"><span class="muted">적의 최종 관통 저항</span><b>${fmt(state.auto?.enabled?AUTO.resistance(AUTO.config(state).target,'pierce',r.autoReport?.rrs||[]):GD.rrValue(state.target,'pierce'),1)}%</b></div><div class="mini-row"><span class="muted">기준 공속 / 모드</span><b>${fmt(state.combat.referenceSpeed)}% / ${(state.auto?.enabled?state.auto.timing.mode==='measured':state.combat.timingMode==='measured')?'실측 빈도 고정':'동작 시간 추정'}</b></div><div class="track"><i style="width:${r.uptime*100}%"></i></div><div class="tiny muted">¹ 피해 증가·스킬 계수 적용 전, 모든 직접 피해 유형 합계입니다.</div>`)+panel('직접 피해 구성','공격 1회가 아닌 초당 기여도',dist.map((x,i)=>`<div class="mini-row"><span>${esc(x.name)}</span><b>${short(x.dps)}</b></div><div class="track ${i%3===1?'gold':i%3===2?'blue':''}"><i style="width:${r.direct?100*x.dps/r.direct:0}%"></i></div>`).join('')+(r.extra?`<div class="mini-row"><span class="muted">지속·별자리·보조 공격</span><b>${short(r.extra)}</b></div>`:''))+panel('주의할 가정','게임 내 실측으로 확인할 항목',`<ul class="warning-list">${r.warnings.slice(0,5).map(w=>`<li>${esc(w)}</li>`).join('')}<li>동작 시간·명중 탄환 수·버프 상태는 사용자 입력입니다.</li><li>전투 전체 DPS는 이동·재시전·대상에 따라 달라집니다.</li><li>차원 30·40단 클리어 여부를 판정하지 않습니다.</li></ul>`);
}
function gearView(){
 const e=state.equipment[slot],p=e.parts[part],title=SLOTS.find(x=>x[0]===slot)?.[1];
 const validParts=PARTS.filter(([k])=>slot!=='relic'||['item','ascension'].includes(k));
 return `<section class="panel"><div class="panel-head"><div><h2>장비 구성</h2><div class="panel-sub">부위 → 아이템 검색 → 장착. 옵션을 하나씩 입력할 필요가 없습니다.</div></div><button class="btn primary" data-action="library">${icon('search')} 아이템 검색</button></div><div class="equipment-layout"><div class="slot-list">${SLOTS.map(([id,label])=>{const a=state.equipment[id];return `<button class="slot ${slot===id?'active':''}" data-action="slot" data-slot="${id}" aria-label="${label} 편집"><span class="slot-icon">${icon(id==='main'||id==='off'?'gun':id==='head'?'helmet':id.includes('ring')||id==='amulet'?'ring':id==='boots'?'boots':'gear')}</span><span class="slot-copy"><small>${label}</small><strong>${esc(a.parts.item.name||'빈 슬롯')}</strong><span class="slot-status ${a.parts.item.db?'ok':''}">${a.parts.item.db?'DB 옵션 연결':'아이템 선택 대기'}</span></span></button>`;}).join('')}</div><div class="editor"><div class="row between"><h3>${title}</h3>${check('계산에 포함',`equipment.${slot}.enabled`)}</div><div class="part-tabs">${validParts.map(([k,l])=>`<button class="${part===k?'active':''}" data-action="part" data-part="${k}">${l}${e.parts[k].db?' ✓':''}</button>`).join('')}</div>${dbEquipped(p)}<div class="row" style="margin:14px 0"><button class="btn primary" data-action="library">${icon('search')} ${p.db?'다른 아이템 검색':'검색해서 장착'}</button><button class="btn small danger" data-action="clear-part">비우기</button></div>${state.auto?.enabled?'<div class="inline-message">자동 모드는 DB 원본 옵션과 롤 선택을 사용합니다. 수동 장비 숫자는 중복 합산하지 않습니다. 실제 시드를 완전히 재현하지는 않습니다.</div>':`<details class="manual-edit"><summary>구버전 수동 항목</summary>${field('이름',`equipment.${slot}.parts.${part}.name`,{type:'text'})}${statsFields(`equipment.${slot}.parts.${part}.stats`)}</details>`}${field('장비 메모',`equipment.${slot}.notes`,{type:'text'})}</div></div></section>
 ${state.auto?.enabled?panel('장비 외 효과도 연결됩니다','캐릭터·스킬·별자리 탭에서 포인트를 선택하세요.',`<div class="auto-keyline">숙련도 → 능력치 · 장비의 +스킬 → 최종 레벨 · 선택한 별 → 패시브/발동 자동 합산</div><p class="hint">자동 모드는 구버전 수동 ‘장비 외 합계’를 더하지 않습니다. 중복 계산을 방지하며, 각 기여도는 검증·출처 탭에 표시합니다.</p>`):''} `;
}

function skillsView(){return panel('기본 공격과 시간','공격 속도만으로 실제 공격 동작 시간을 확정할 수 없습니다.',`<div class="field-grid three">${field('기본 공격 이름','combat.darName',{type:'text'})}${field('기본 공격 무기 피해 %','combat.darWD',{min:0,step:.1,hint:'장비의 +%p는 장비 칸에서 추가'})}${field('별도 총피해 변경 %','combat.totalDamageModifier',{min:-100,step:.1})}${field('기준 공격 속도 %','combat.referenceSpeed',{min:1,max:1000,hint:'아래 동작 시간을 측정한 공속'})}${field('공격 속도 상한 %','combat.speedCap',{min:1,max:1000})}${field('사격 유지율 %','combat.uptime',{min:0,max:100,hint:'이동·회복·디버프 시전 시간 제외'})}${select('공격 빈도 계산','combat.timingMode',[['cycles','공격별 동작 시간 사용'],['measured','실측한 평균 횟수 고정']])}${field('평균 공격 동작 / 초','combat.measuredAPS',{min:0,max:100,step:.01,hint:'빈도 고정 모드에서만 적용'})}${field('일반 공격 동작 시간 ms','combat.basicCycleMs',{min:20,max:20000})}</div><div class="row" style="margin:14px 0">${check('쌍수 무기 사용','combat.dual')}</div><details><summary>기본 공격 자체의 추가 피해 · 전용 관통 전환</summary><div class="field-grid three">${GD.TYPES.map(t=>field(`${GD.LABELS[t]} 추가 피해`,`combat.darFlat.flat_${t}`,{min:0,step:.1})).join('')}${field('냉기 → 관통 % (스킬)','combat.skillConversion.conv_cold',{min:0,max:100})}${field('원소 → 관통 % (스킬)','combat.skillConversion.conv_elemental',{min:0,max:100})}</div></details><div class="hint">맹공격/발동 사격의 숫자는 예제 참조값입니다. 레벨을 입력하면 자동으로 수치를 가져오는 스킬 DB는 포함되지 않습니다. 실제 최종 계수를 직접 확인하세요.</div>`)+
 panel('발동 사격 풀','탄환 수는 발사 수가 아닌, 한 대상에게 실제로 맞는 기대 타격 수입니다.',`<div class="scroll-table"><table><thead><tr><th>사용</th><th>사격</th><th>발동 %</th><th>무기 피해 %</th><th>주무기 타격</th><th>보조 타격</th><th>시간 ms</th><th></th></tr></thead><tbody>${state.wps.map((r,i)=>`<tr><td><input aria-label="${esc(r.name)} 사용" type="checkbox" data-bind="wps.${i}.enabled" ${r.enabled!==false?'checked':''}></td><td class="cell-name"><input aria-label="사격 이름" data-bind="wps.${i}.name" type="text" value="${esc(r.name)}" style="width:125px"></td>${[['chance',0,1000,.1],['wd',0,5000,.1],['hitsMain',0,50,.1],['hitsOff',0,50,.1],['cycleMs',20,20000,1]].map(([key,min,max,step])=>`<td><input aria-label="${esc(r.name)} ${key}" type="number" min="${min}" max="${max}" step="${step}" data-bind="wps.${i}.${key}" value="${esc(r[key])}"></td>`).join('')}<td><button class="btn small ghost" data-action="delete-wps" data-index="${i}" aria-label="${esc(r.name)} 삭제">×</button></td></tr>`).join('')}</tbody></table></div><div class="tag-legend">시간은 ‘기준 공격 속도’에서 측정한 1회 동작 길이입니다. 초과 발동 확률은 정규화됩니다. 승천 추가 확률은 장비 칸에 입력하세요.</div><button class="btn small" data-action="add-wps">${icon('plus')} 발동 사격 추가</button>${state.wps.map((r,i)=>`<details><summary>${esc(r.name)} · 추가 피해와 전환</summary><div class="field-grid three">${GD.TYPES.map(t=>field(`${GD.LABELS[t]} 추가 피해`,`wps.${i}.flat.flat_${t}`,{min:0,step:.1})).join('')}${field('냉기 → 관통 % (스킬)','wps.'+i+'.conversion.conv_cold',{min:0,max:100})}${field('번개 → 관통 % (스킬)','wps.'+i+'.conversion.conv_lightning',{min:0,max:100})}</div></details>`).join('')}`)+
 panel('지속 피해 · 별자리 · 추가 발동','주력 사격과 별도로 유지되는 DPS를 입력합니다. 무한 중첩하지 않습니다.',`<div class="note-block">기본 피해와 피해 증가율·치명타를 이미 반영한 <strong>1초당 유지 피해</strong>를 입력하세요. 저항 전/후만 아래에서 구분합니다. 같은 출처 ID의 같은 지속 피해는 가장 높은 값만 반영됩니다. 치명타 스냅샷과 재적용을 자동 계산하지 않습니다.</div>${state.extras.map((x,i)=>`<details open><summary>${esc(x.name||'추가 피해')}</summary><div class="field-grid three">${field('이름',`extras.${i}.name`,{type:'text'})}${select('분류',`extras.${i}.kind`,[['dot','지속 피해'],['proc','별도 발동']])}${select('피해 유형',`extras.${i}.type`,[...GD.TYPES,'bleed'].map(t=>[t,GD.LABELS[t]]))}${field('지속 피해 출처 ID',`extras.${i}.group`,{type:'text'})}${field('유지 DPS',`extras.${i}.rate`,{min:0,step:1})}${field('유지율 %',`extras.${i}.uptime`,{min:0,max:100})}</div><div class="row between" style="margin-top:12px">${check('이미 적의 경감이 적용된 값',`extras.${i}.afterMitigation`)}<button class="btn small danger" data-action="delete-extra" data-index="${i}">삭제</button></div></details>`).join('')}<button class="btn small" style="margin-top:13px" data-action="add-extra">${icon('plus')} 추가 피해 입력</button>`);
}
function targetView(){return panel('측정 대상','차원 단계가 아니라, 실제 적의 최종 능력치를 기준으로 비교합니다.',`<div class="field-grid three">${field('대상 이름','target.name',{type:'text'})}${field('적 방어 능력','target.da',{min:0})}${field('적 방어 능력 감소 (환산치)','target.daReduction',{min:0,hint:'여러 종류의 감소를 이미 환산한 값'})}${field('적 방어구 / 물리 피해','target.armor',{min:0})}${field('적 방어구 흡수율 %','target.armorAbsorption',{min:0,max:100})}${field('적 피해 흡수 %','target.absorption',{min:0,max:100})}${field('적의 타격당 고정 흡수','target.flatAbsorption',{min:0})}${field('빗맞힘·회피 통합 확률 %','target.avoidance',{min:0,max:100})}${select('저항 입력 방식','target.resistMode',[['final','최종 저항 직접 입력'],['base','기본 저항 − 등록한 감소']])}</div><div class="hint">대상의 종족 보정, 방어구 파괴, 저항 상한 변화 등은 이미 반영한 값을 입력하세요. SR 30/40단 적 능력치를 임의로 자동 지정하지 않습니다.</div>`)+panel('피해 유형별 저항',state.target.resistMode==='final'?'모든 디버프를 반영한 최종 저항입니다. 음수 입력이 가능합니다.':'디버프 적용 전 저항입니다. 아래 등록한 저항 감소를 적용합니다.',`<div class="field-grid three">${[...GD.TYPES,'bleed'].map(t=>field(`${GD.LABELS[t]} 저항 %`,`target.resists.${t}`,{min:-500,max:1000,step:.1})).join('')}</div>`)+panel('저항 감소 출처','-%p 합산형과 고정 감소 중 최댓값만 지원합니다.',`<div class="notice info">${icon('info')}<div><strong>최종 저항 직접 입력 모드에서는 이 목록을 적용하지 않습니다.</strong> ‘% reduced target resistance’ 같은 곱셈형, 복잡한 유지율은 최종 저항으로 환산해서 입력하세요. 같은 디버프 ID는 중복 합산하지 않습니다.</div></div>${state.target.rr.map((r,i)=>`<div class="field-grid three" style="margin-bottom:16px">${field('출처 이름',`target.rr.${i}.name`,{type:'text'})}${field('같은 디버프 ID',`target.rr.${i}.group`,{type:'text'})}${select('유형',`target.rr.${i}.type`,[['all','모든 저항'],...[...GD.TYPES,'bleed'].map(t=>[t,GD.LABELS[t]])])}${select('방식',`target.rr.${i}.kind`,[['stack','-%p 합산형'],['flat','고정 감소 · 최댓값']])}${field('감소 수치 (양수)',`target.rr.${i}.value`,{min:0,step:.1})}<div class="row">${check('사용',`target.rr.${i}.enabled`)}<button class="btn small danger" data-action="delete-rr" data-index="${i}">삭제</button></div></div>`).join('')}<button class="btn small" data-action="add-rr">${icon('plus')} 저항 감소 추가</button>`);}
function analysisView(){return `<div id="analysis-dynamic"></div>`;}
function renderAnalysisDynamic(){
 const r=result;const duration=GD.clamp(state.duration,5,300);const sim=GD.simulate(state,duration,state.seed),a=GD.analyzeEvents(sim.events,{start:0,end:duration,window:5,step:.5});
 const changed=fn=>{const s=GD.copy(state);fn(s);return GD.calculate(s).total;};
 const values=[['공격 능력 +200 (최종)',changed(s=>s.base.oa=GD.n(s.base.oa)+200/Math.max(.01,1+GD.n(r.a.g.oaPct)/100))],['사격 유지율 100%',changed(s=>s.combat.uptime=100)],['관통 저항 20%p 더 감소',changed(s=>s.target.resists.pierce=GD.n(s.target.resists.pierce)-20)],['모든 동작 시간 +20%',changed(s=>{s.combat.timingMode='cycles';s.combat.basicCycleMs*=1.2;s.wps.forEach(w=>w.cycleMs*=1.2);})]];
 $('#analysis-dynamic').innerHTML=panel('5초 구간 DPS · 모의 기록','같은 시드의 확률적 예시입니다. 실제 DPYes 측정값이나 오차 신뢰구간이 아닙니다.',`<div class="field-grid three">${field('모의 전투 길이 · 초','duration',{min:5,max:300})}${field('재현용 난수 시드','seed',{min:1,max:999999})}<div class="row" style="align-items:end"><button class="btn small" data-action="simulation-log">모의 기록을 로그 탭으로</button></div></div><div style="margin-top:20px">${chart(a.points,210,r.total)}</div><div class="legend"><span><i></i>모의 기록 · 5초 평균</span><span style="color:var(--gold)">- - 이론상 전투 평균</span></div><div class="hint">명중·치명타·발동 사격을 독립 추첨합니다. 이동은 평균 유지율로 늘인 간격으로 단순화합니다. 투사체 도달 시간, 실제 버프·디버프 시작 지연은 재현하지 않습니다.</div>`)+
 panel('주력 사격 계산 내역','DPS = 기대 피해 / 기대 동작 시간. 각 공격의 DPS를 단순 평균하지 않습니다.',`<div class="scroll-table"><table><thead><tr><th>공격</th><th>실제 비중</th><th>공격당 기대 피해</th><th>동작 시간</th><th>전투 DPS</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${fmt(x.p*100,2)}%</td><td>${fmt(x.damage)}</td><td>${fmt(x.seconds*1000,1)}ms</td><td style="color:var(--green)">${fmt(x.dps)}</td></tr>`).join('')}</tbody></table></div><div class="split" style="margin-top:16px"><div class="note-block"><strong>평균 피해 / 평균 시간</strong><br>${fmt(r.meanDamage,1)} / ${fmt(r.meanCycle,4)}초<br>고정 빈도 모드: ${state.combat.timingMode==='measured'?'사용':'미사용'}</div><div class="note-block"><strong>명중·치명타 계수</strong><br>PTH ${fmt(r.profile.pth,3)} · 평균 ${fmt(r.profile.mean,4)}배<br>물리 방어구·고정 흡수는 각 치명타 구간에 따로 적용</div></div>`)+
 panel('어느 변화가 더 큰가요?','한 항목씩만 변경한 입력 민감도입니다. 추가 옵션의 파밍 가능성을 보장하지 않습니다.',`<table><thead><tr><th>변경 조건</th><th>예상 DPS</th><th>현재 대비</th></tr></thead><tbody>${values.map(([l,v])=>{const d=r.total?(v/r.total-1)*100:0;return `<tr><td>${l}</td><td>${fmt(v)}</td><td class="${d>=0?'pos':'danger-text'}">${d>=0?'+':''}${fmt(d,1)}%</td></tr>`;}).join('')}</tbody></table>`)+
 panel('피해 유형과 산탄 명중','관통으로 전환되지 않은 직접 피해도 각 유형의 저항으로 계산합니다.',`<div class="stats-grid">${Object.entries(r.types).filter(([,v])=>v>.001).map(([t,v])=>`<div class="metric-mini statbreak"><span class="muted">${GD.LABELS[t]}</span><b>${fmt(v)} / s</b></div>`).join('')||'<div class="empty">피해 입력이 없습니다.</div>'}</div>${state.wps.some(w=>w.id==='storm')?`<hr class="sep"><h3>폭풍 분사 · 한 대상 명중 탄환 수</h3><table><thead><tr><th>총 타격 수</th><th>예상 전투 DPS</th></tr></thead><tbody>${[2,4,6,8].map(n=>`<tr><td>${n}발</td><td>${fmt(changed(s=>{const w=s.wps.find(x=>x.id==='storm');w.hitsMain=n/2;w.hitsOff=n/2;}))}</td></tr>`).join('')}</tbody></table>`:''}`);
}
function logsView(){
 const fields=logData.rows.length?Object.keys(GD.flatten(logData.rows[0])):[];
 const mappingSelect=(key,label,none=false)=>`<label class="field">${label}<select data-logmap="${key}">${none?'<option value="">미지정</option>':'<option value="">필드 선택</option>'}${fields.map(f=>`<option value="${esc(f)}" ${logData.map[key]===f?'selected':''}>${esc(f)}</option>`).join('')}</select></label>`;
 return panel('DPYes 기록 불러오기','파일은 서버로 전송되지 않습니다. 데이터 배열과 숫자 필드를 직접 확인합니다.',`<div class="upload-zone">${icon('upload')}<h3 style="margin:10px 0 4px">피해 기록 JSON 또는 CSV</h3><div class="small muted">DPYes의 기록 형식은 버전별로 다를 수 있습니다. 필드를 매핑한 뒤 분석합니다.</div><div class="row" style="justify-content:center;margin-top:16px;flex-wrap:wrap"><button class="btn primary" data-action="import-log">파일 선택</button><button class="btn" data-action="sample-log">모의 예제 기록</button><button class="btn ghost" data-action="log-schema">입력 예시 보기</button></div></div>${logData.rows.length?`<div class="inline-message">${esc(logData.fileName)} · ${fmt(logData.rows.length)}행 · ${logData.sample?'모의 기록 (실측 아님)':'사용자 파일'}</div><div class="field-grid three"><label class="field">데이터 배열<select data-log="arrayPath">${logData.arrays.map((a,i)=>`<option value="${i}" ${logData.arrayIndex===i?'selected':''}>${esc(a.path)} (${a.rows.length})</option>`).join('')}</select></label>${mappingSelect('time','시간 필드')}${mappingSelect('damage','피해량 필드')}<label class="field">시간 단위<select data-logmap="unit">${[['s','초'],['ms','밀리초'],['us','마이크로초']].map(([v,l])=>`<option ${logData.map.unit===v?'selected':''} value="${v}">${l}</option>`).join('')}</select></label>${mappingSelect('skill','스킬 필드',true)}${mappingSelect('target','피격 대상 필드',true)}${mappingSelect('source','공격 주체 필드',true)}<label class="field">입력 피해 기준<select data-log="mitigation">${[['unknown','모름 · 비교 주의'],['after','경감 후 피해'],['before','경감 전 피해']].map(([v,l])=>`<option value="${v}" ${logData.mitigation===v?'selected':''}>${l}</option>`).join('')}</select></label></div><div class="row" style="margin:15px 0"><label class="check"><input type="checkbox" data-logmap="relative" ${logData.map.relative!==false?'checked':''}>파일의 첫 이벤트를 0초로 이동 (필터 전)</label></div><details><summary>첫 3행 · 원본 필드 확인</summary><pre class="code">${esc(JSON.stringify(logData.rows.slice(0,3),null,2))}</pre></details><div class="hint">받은 피해·펫·여러 대상을 섞지 않도록 공격 주체와 피격 대상 필드를 지정하세요. 시간 정보가 없는 파일은 DPS로 환산하지 않습니다.</div><button class="btn primary" data-action="apply-log">매핑 확인 · 분석</button>`:''}`)+`<div id="log-analysis"></div>`;
}
function renderLogAnalysis(){
 if(!$('#log-analysis')||!logData.events.length)return;
 const sources=[...new Set(logData.events.map(e=>e.source))],targets=[...new Set(logData.events.map(e=>e.target))];
 const filtered=logData.events.filter(e=>(logData.filterSource==='all'||e.source===logData.filterSource)&&(logData.filterTarget==='all'||e.target===logData.filterTarget));
 let a;try{a=GD.analyzeEvents(filtered,{start:logData.start,end:logData.end,window:logData.window,step:.25});}catch(e){$('#log-analysis').innerHTML=`<div class="notice">${esc(e.message)}</div>`;return;}
 const filter=(key,label,vals)=>`<label class="field">${label}<select data-log="${key}"><option value="all">전체</option>${vals.map(v=>`<option value="${esc(v)}" ${logData[key]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;
 $('#log-analysis').innerHTML=panel(logData.sample?'모의 기록 분석':'사용자 기록 분석','누적 피해 ÷ 지정한 실제 전투 시간. 무피해 시간도 분모에 포함합니다.',`<div class="field-grid three">${filter('filterSource','공격 주체',sources)}${filter('filterTarget','피격 대상',targets)}<label class="field">이동 평균 창 · 초<input type="number" min=".1" max="120" step=".1" data-log="window" value="${logData.window}"></label><label class="field">시작 · 초<input type="number" min="0" step=".1" data-log="start" value="${logData.start}"></label><label class="field">종료 · 초<input type="number" min=".1" step=".1" data-log="end" value="${logData.end}"></label><div class="row" style="align-items:end"><button class="btn small" data-action="export-log">필터 기록 CSV</button></div></div><div class="hint">종료 시간은 초기 제안값입니다. <strong>실제 측정 시간으로 수정</strong>하세요. 마지막 타격 시간만으로 전투 종료를 확정하지 않습니다. 필터를 바꿔도 시간 원점과 전투 길이는 유지됩니다.</div><div class="field-grid three"><div class="metric-mini"><span class="tiny muted">전투 전체 평균</span><div class="big">${fmt(a.average)}</div><span class="tiny muted">${fmt(a.duration,1)}초 · ${fmt(a.count)}개 기록</span></div><div class="metric-mini"><span class="tiny muted">${logData.window}초 창 최고값</span><div class="big">${a.peak===null?'—':fmt(a.peak)}</div><span class="tiny muted">초기 ${logData.window}초 미만 구간 제외</span></div><div class="metric-mini"><span class="tiny muted">누적 피해</span><div class="big">${short(a.total)}</div><span class="tiny muted">${logData.skipped}행 무효/누락 제외</span></div></div><div style="margin-top:22px">${chart(a.points,235,a.average)}</div><div class="legend"><span><i></i>${logData.window}초 이동 평균</span><span style="color:var(--gold)">- - 전투 전체 평균</span></div><div class="notice info" style="margin-top:16px;margin-bottom:0">${icon('info')}<div>${logData.sample?'이 기록은 앱에서 만든 예제이며 실제 DPYes 로그가 아닙니다.':`현재 입력: <strong>${logData.mitigation==='after'?'경감 후':logData.mitigation==='before'?'경감 전':'경감 전/후 미확인'}</strong>. 서로 다른 집계 설정을 비교하지 마세요.`} 이 앱은 최대 ${logData.window}초의 정확한 창으로 재집계합니다. DPYes의 내부 틱·초기화·일시정지 처리와 동일하다고 보장하지 않습니다.</div></div>`)+panel('기록의 피해 출처','로그 필드에 기록된 이름을 기준으로 집계합니다.',`<table><thead><tr><th>스킬 / 출처</th><th>누적 피해</th><th>전투 평균 DPS</th><th>비중</th></tr></thead><tbody>${Object.entries(a.groups).sort((x,y)=>y[1]-x[1]).slice(0,50).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${fmt(v)}</td><td>${fmt(v/a.duration)}</td><td>${fmt(a.total?v/a.total*100:0,1)}%</td></tr>`).join('')}</tbody></table><div class="note-block" style="margin-top:16px"><strong>예측과 비교</strong><br>현재 입력 예측 ${fmt(result.total)} / 기록 평균 ${fmt(a.average)}<br>같은 대상·버프·사격 유지율·경감 설정일 때만 비교 의미가 있습니다. 기록에 맞추기 위해 결과를 자동 배율 보정하지 않습니다.</div>`);
}
function legacyHelpView(){return panel('이 사이트가 계산하는 것','장비 기반 예상값과 DPYes의 실측 집계를 분리했습니다.',`<div class="notice info">${icon('info')}<div><strong>DPYes에는 장비 → DPS라는 단일 예측식이 없습니다.</strong> 실제 발생한 피해를 시간으로 나누는 측정 도구입니다. 이 앱의 예측 엔진은 공개된 게임 전투 규칙을 이용한 별도의 모델입니다.</div></div>${[
 ['옵션 합산','무기의 고정 피해는 해당 손에만, 방어구·장신구의 고정 피해는 두 손에 적용합니다. 피해 증가와 공격 능력은 전역 합산합니다. 최종 OA = 고정 OA 합계 × (1 + OA 증가율/100). 교활·숙련도 등은 환산 후 장비 외 합계에 입력합니다.'],
 ['관통 전환','스킬 전환 → 전역 전환 → 남은 물리의 Armor Piercing 순서입니다. 이미 변환된 피해를 다시 변환하지 않습니다. 이 버전은 관통으로의 단방향 전환만 지원합니다. 원소 고정 피해는 화염·냉기·번개로 3등분합니다.'],
 ['무기 공격과 발동 사격','탄환당 피해 = [무기 기반 피해 × 기본 공격 계수 × 발동 사격 계수 + 기본 공격 자체 추가 피해 + 발동 사격 자체 추가 피해] × 유형별 증가율. 고정 피해는 가산, 무기 피해 계수는 곱하는 공개 실험 모델입니다. 개별 스킬의 예외는 최종 계수로 수동 보정해야 합니다.'],
 ['발동 비중과 동작 시간','합계 100% 이하는 남는 확률을 기본 공격으로, 100% 초과는 각 확률/합계로 정규화합니다. 초당 직접 피해 = Σ(선택 비중 × 공격당 기대 피해) / Σ(선택 비중 × 동작 시간) × 사격 유지율. 100% 속도 자체가 공격 횟수를 뜻하지 않습니다.'],
 ['명중·치명타·경감','공식 PTH 식과 90/105/120/130/135 구간을 연속 확률 모델로 사용합니다. 100 초과는 PTH 길이에서 표본화합니다. 저항, 남은 물리 피해에 대한 방어구, % 흡수, 타격당 고정 흡수를 각 치명타 구간에 따로 적용합니다.'],
 ['지속 피해와 별도 발동','주력 공격 속도에 출혈을 단순 곱하지 않습니다. 사용자가 환산한 유지 DPS와 유지율을 별도로 입력합니다. 같은 피해 유형·출처 ID는 최댓값만 적용합니다. 재적용·치명타 스냅샷 경쟁·펫 AI를 정밀 시뮬레이션하지 않습니다.'],
 ['DPYes 로그 재집계','전체 평균 = 지정한 구간의 실제 피해 합계 / (종료−시작). 이동 평균 = (t−W, t] 구간의 피해 / min(W, t−시작). 시작 순간의 이벤트는 초기 창에 포함합니다. 최고값은 최소 W초가 지난 이벤트 시점에서 찾습니다. 초기 부분 창은 최고값 경쟁에서 제외합니다.']
 ].map(([t,d],i)=>`<div class="math-step"><span class="num">0${i+1}</span><div><strong>${t}</strong><p>${d}</p></div></div>`).join('')}<pre class="code" style="margin-top:18px">PTH = max(55, 90·OA / (OA + DA/3.5) + 0.02275·(OA−DA) + 20)

DPS_direct = E[damage per action] / E[time per action] × uptime
DPS_total  = DPS_direct + entered sustained / proc DPS

Rolling_W(t) = Σ damage in (t−W, t] / min(W, t−start)</pre>`)+
 panel('지원 범위와 제한','숫자가 정밀해 보여도 입력 이상의 정확도를 갖지는 않습니다.',`<table style="white-space:normal"><thead><tr><th style="width:27%">지원</th><th>설명</th></tr></thead><tbody><tr><td>장비 14부위</td><td>본체·접두·접미·컴포넌트·증강제·유물을 공개 DB에서 검색해 자동 입력합니다. 승천은 별도 수동 보정입니다.</td></tr><tr><td>주력 직접 피해 9유형</td><td>관통 중심 변환, 저항별 피해. 다른 방향의 복합 전환은 외부에서 환산해야 합니다.</td></tr><tr><td>일반 쌍수 기본 공격</td><td>기본 공격에 주무기 25%, 보조 25%, 양손 50%의 공개 실험 모델. 다른 예외는 타격 수로 반영.</td></tr><tr><td>예제와 템플릿</td><td>첫 실행에서 공개 게임 추출 DB를 자동 다운로드합니다. 서약운반자 버튼은 이름이 일치하는 본체·부품·증강제를 실제 데이터로 장착합니다. 중복·미검색 항목은 따로 표시합니다.</td></tr><tr><td>게임 저장 파일 / 링크</td><td>GrimTools 빌드 URL, .gdc, 실시간 게임 메모리 직접 연동 미지원.</td></tr><tr><td>생존과 SR 단계</td><td>체력·DA 합산값은 참고용. 모든 방어 효과나 차원 난이도를 시뮬레이션하지 않습니다.</td></tr><tr><td>로그 매핑</td><td>JSON 배열·CSV의 숫자 시간/피해 필드가 필요합니다. 시간 없는 합계 파일로 DPS를 지어내지 않습니다.</td></tr></tbody></table><div class="hint">아이템의 자체 기본 피해를 입력할 때, 이미 캐릭터 창 피해 증가가 적용된 숫자를 넣지 마세요. 툴팁 붙여넣기는 보조 기능이므로 변환 결과를 반드시 확인합니다.</div>`)+
 panel('근거 자료','아이템 데이터 버전은 상단에 표시됩니다. 예제 전투 조건은 게임 실측치가 아닙니다.',SOURCES.map(([name,desc,url])=>`<div class="source-card"><a href="${url}" target="_blank" rel="noopener noreferrer">${esc(name)} ↗</a><p>${esc(desc)}</p></div>`).join(''))+
 panel('데이터와 실행','계정 없이 로컬에서 사용합니다.',`<p class="small muted">START_WINDOWS.cmd로 실행하면 공개 DB를 내려받아 127.0.0.1에서 제공합니다. 사용자 빌드·로그는 외부로 전송하지 않습니다. 최초 데이터 준비 후 DB 포함 HTML을 저장하면 서버 없이도 검색할 수 있습니다.</p><p class="small muted">그림툴 공식 API를 사용하거나 접근 제한을 우회하지 않습니다. 데이터는 화면에 표시된 버전의 공개 추출 스냅샷이며, 최종 스킬·세트·발동·승천 효과가 모두 자동 계산되는 것은 아닙니다.</p>`);
}
function helpView(){if(state.auto?.enabled)return AUTOUI.help();return panel('v3 자동 계산 사용 순서','아이템 옵션과 스킬 계수를 직접 옮겨 적을 필요를 줄였습니다.',`<div class="math-step"><span class="num">01</span><div><strong>장비 검색 → 장착</strong><p>공개 DB의 본체·접사·부품·증강제를 선택합니다. 없는 데이터는 임의로 채우지 않습니다.</p></div></div><div class="math-step"><span class="num">02</span><div><strong>캐릭터 → 스킬 → 별자리</strong><p>두 직업, 능력치 투자량, 스킬 포인트, 별을 선택합니다. 장비로 오르는 스킬 레벨·계수와 세트 보너스가 자동 적용됩니다.</p></div></div><div class="math-step"><span class="num">03</span><div><strong>대상·회전 → 검증·출처</strong><p>대상 방어 능력·저항과 실제 공격 유지율을 정합니다. 제외 효과와 가정이 많으면 예측을 전체 DPS로 취급하지 마세요.</p></div></div><div class="notice"><b>전체 게임 엔진 재현이 아닙니다.</b> 데이터에 있는 모든 스킬을 탐색하고 레벨 수치를 연결하지만 펫 AI, 변신, 카덴스 특수 순서, 일부 파편/반격/승천 예외는 총피해에서 제외됩니다. 성장 기본값·공격 동작 시간에도 표시된 근사가 있습니다.</div>`)+panel('출처와 재현','데이터 스냅샷 버전과 검증 결과를 함께 확인하세요.',SOURCES.map(([name,desc,url])=>`<div class="source-card"><a href="${url}" target="_blank" rel="noopener noreferrer">${esc(name)} ↗</a><p>${esc(desc)}</p></div>`).join(''))+panel('Windows 실행 검증 상태','테스트 절차를 제공하는 것과 실제 실행 완료는 다릅니다.',`<p>이 배포에는 Windows 최초 실행 → 실제 DB 다운로드 → Chromium 계산 → 오프라인 재실행 → 캐시 재실행을 검사하는 GitHub Actions 작업과 PowerShell 테스트가 포함됩니다. 현재 제작 환경은 Linux이므로 Windows 작업 실행 결과는 아직 없습니다. TEST_REPORT.json에서 실제 수행 여부를 확인하세요.</p><p>DPYes는 실제 피해 로그를 집계합니다. 이 앱의 예측은 별도 근사 모델입니다. 최고 5초 DPS를 전투 전체 평균과 혼동하지 마세요.</p>`);}

function openModal(title,body){lastFocus=document.activeElement;$('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="panel-head"><h2>${title}</h2><button class="btn small ghost" data-action="close-modal" aria-label="닫기">${icon('close')}</button></div><div class="modal-body">${body}</div></section></div>`;setTimeout(()=>$('.modal input,.modal textarea,.modal button')?.focus(),0);}
function closeModal(){$('#modal-root').innerHTML='';lastFocus?.focus?.();libraryTarget=null;}
let dbSelected=null,dbPage=0,dbRarity='',dbMax=100,dbRoll='mean';
function dbStatus(){const d=CATALOG.DB;return `<div class="db-connection"><div><span class="badge ${d.phase==='ready'?'good':d.phase==='error'?'':'blue'}">${d.phase==='ready'?(d.data.meta.fixture?'검사 표본 · 실제 DB 아님':'DB 연결됨'):d.phase==='error'?'DB 연결 확인':'DB 준비 중'}</span><strong>${esc(d.phase==='ready'?d.message:d.phase==='error'?'검색 데이터를 불러오지 못했습니다':d.message)}</strong><div class="tiny muted">${d.phase==='ready'?`게임 데이터 ${esc(d.data.meta.gameVersion)} · 공개 추출 스냅샷 · 그림툴 공식 연동 아님`:esc(d.message)}</div></div><div class="row"><button class="btn small" data-action="db-help">연결·범위</button><button class="btn small" data-action="portable" ${d.phase!=='ready'?'disabled':''}>DB 포함 HTML 저장</button></div></div>${d.phase==='loading'?`<div class="track"><i style="width:${d.progress}%"></i></div>`:''}`;}
function dbStatsList(stats){return Object.entries(stats||{}).map(([k,v])=>`<div class="mini-row"><span>${esc(FIELD_LABELS[k]||({armor:'방어구 (표시)',armorPct:'방어구 증가 % (표시)',physique:'체격 (파생 미반영)',cunning:'교활 (파생 미반영)',spirit:'정신 (파생 미반영)',healingPct:'회복 증가 % (표시)'}[k])||k)}</span><b>${fmt(v,2)}</b></div>`).join('')||'<p class="muted">현재 엔진에 직접 적용할 고정 옵션이 없습니다.</p>';}
function dbEquipped(p){if(!p.db)return '<div class="note-block">이 항목은 아직 검색 DB와 연결되지 않았습니다. <strong>아이템 검색</strong>에서 선택하면 옵션 숫자가 자동으로 채워집니다.</div>';
 return `<div class="db-equipped"><div class="row between"><span class="badge good">DB 옵션 자동 적용</span><span class="tiny muted">${esc(p.db.gameVersion)} · ${esc(p.db.roll==='low'?'하한':p.db.roll==='high'?'상한':'기준 평균')}</span></div><h3>${esc(p.name)}</h3><div class="small muted">${esc(p.db.en||'')} · 레벨 ${fmt(p.db.level)}</div><div class="auto-stats">${dbStatsList(p.stats)}</div><details><summary>스킬 보너스 · 자동 계산 제외 항목 (${(p.db.unapplied||[]).length})</summary>${(p.db.boosts||[]).map(b=>`<p class="small">${esc(b.name)} +${b.level} <span class="muted">— 최종 스킬 계수에는 별도 반영 필요</span></p>`).join('')} ${(p.db.unapplied||[]).map(u=>`<p class="small muted">${esc(u.name||'')}: ${esc(u.stat||u.reason)} ${fmt(u.value??u.min??0,2)} · ${esc(u.reason)}</p>`).join('')}<div class="hint">자동 가져온 옵션과 최종 스킬 레벨 계산은 별개입니다. 세트·발동 효과·능력치 파생 효과 중 미지원 항목은 총피해에 자동 합산하지 않습니다.</div></details><div class="row" style="margin-top:12px"><button class="btn small" data-action="reroll-db" data-roll="low">하한</button><button class="btn small" data-action="reroll-db" data-roll="mean">기준 평균</button><button class="btn small" data-action="reroll-db" data-roll="high">상한</button><button class="btn small ghost" data-action="source-db">원본 레코드</button></div><div class="tiny muted" style="margin-top:8px">하한·상한은 옵션별 공개 범위의 비교용 극단값입니다. 실제 랜덤 시드의 완벽한 재현이나 동시 획득 보장은 아닙니다.</div></div>`;
}
function libraryModal(){libraryTarget={slot,part};dbPage=0;dbSelected=null;dbRarity='';dbRoll='mean';
 openModal('아이템 검색 · 옵션 자동 입력',`${CATALOG.DB.data?.meta.testOnly?'<div class="hint">UI 검사 표본입니다. 실제 전체 DB 또는 완성 캐릭터의 수치를 나타내지 않습니다.</div>':''}<div class="row"><input class="search-input" id="library-search" placeholder="이름 검색 · 서약운반자 / Oathbearer" aria-label="라이브러리 검색"><select id="db-rarity" aria-label="등급"><option value="">모든 등급</option>${['Legendary','Epic','Rare','Magical','Common'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="db-search-sub"><span class="badge blue">${esc(SLOTS.find(x=>x[0]===slot)[1])} · ${esc(PARTS.find(x=>x[0]===part)[1])}</span><label class="small">최대 아이템 레벨 <input id="db-level" type="number" value="100" min="1" max="200" style="width:65px"></label><span class="tiny muted">한글·영문 · 부위 필터 · 중간 롤 적용</span></div><div id="library-results"></div>`);renderLibrary('');
}
function renderLibrary(q){if(!$('#library-results'))return;const db=CATALOG.DB;if(db.phase!=='ready'){$('#library-results').innerHTML=`<div class="empty">${esc(db.message)}<br><button class="btn small" data-action="db-help">설정 안내</button></div>`;return;}
 const base=state.equipment[slot].parts.item.db;const res=db.search(q,slot,part,base,{rarity:dbRarity,maxLevel:dbMax,offset:dbPage*40,limit:40});
 let warn='';if(['prefix','suffix'].includes(part))warn='<div class="hint">접사 데이터는 자동으로 가져옵니다. 동일 이름의 부위별 변형이 있으므로 원본 경로를 확인하세요. 전체 드롭 테이블 기반 접사 조합 적법성은 보장하지 않습니다.</div>';
 if(part==='ascension')warn='<div class="note-block">승천 옵션 전용 규칙은 이 데이터에 포함되지 않습니다. 이 항목은 수동 보정 탭을 사용하세요.</div>';
 $('#library-results').innerHTML=warn+`<div class="db-result-head"><span>${fmt(res.total)}개 결과</span><div class="row"><button class="btn small" data-action="db-page" data-dir="-1" ${dbPage===0?'disabled':''}>이전</button><span class="tiny">${dbPage+1}</span><button class="btn small" data-action="db-page" data-dir="1" ${(dbPage+1)*40>=res.total?'disabled':''}>다음</button></div></div><div class="db-browser"><div class="db-results">${res.rows.map(x=>{const m=CATALOG.mapped(x);return `<button class="db-card ${dbSelected===x.id?'selected':''}" data-action="pick-db" data-id="${esc(x.id)}"><span class="db-type ${/legendary/i.test(x.rarity)?'legendary':/rare/i.test(x.rarity)?'rare':''}">${esc(x.rarity||x.domain)} <span>Lv. ${fmt(x.level)}</span></span><strong>${esc(x.name)}</strong><span class="db-en">${esc(x.en)}</span>${['prefix','suffix','affix'].includes(x.part)?`<span class="tiny code-wrap">${esc(x.id.split('/').slice(-2).join('/'))}</span>`:''}<span class="tiny muted">${Object.entries(m.stats).slice(0,3).map(([k,v])=>`${esc(FIELD_LABELS[k]||k)} ${fmt(v,1)}`).join(' · ')||'상세 효과 보기'}</span></button>`;}).join('')||'<div class="empty">이 부위에서 일치하는 결과가 없습니다.<br>짧은 이름 또는 영문 이름으로 검색하세요.</div>'}</div><div id="db-detail" class="db-detail"><div class="empty">아이템을 선택하면<br>실제 옵션과 장착 버튼이 표시됩니다.</div></div></div>`;
 if(dbSelected&&res.rows.some(x=>x.id===dbSelected))renderDbDetail(dbSelected);
}
function renderDbDetail(id){const item=CATALOG.DB.get(id);if(!item||!$('#db-detail'))return;dbSelected=id;const m=CATALOG.mapped(item,dbRoll);const rq=item.requirements||{};$('#db-detail').innerHTML=`<span class="badge ${/legendary/i.test(item.rarity)?'':'good'}">${esc(item.rarity||item.domain)} · Lv. ${item.level}</span><h3>${esc(item.name)}</h3><p class="small muted">${esc(item.en)}</p><div class="tiny muted">요구 레벨 ${rq.level||'—'} · 체격 ${rq.physique||0} · 교활 ${rq.cunning||0} · 정신 ${rq.spirit||0}</div><div class="row" style="margin:12px 0"><label class="field" style="flex:1">옵션 범위<select id="db-roll"><option value="mean" ${dbRoll==='mean'?'selected':''}>기준 평균</option><option value="low" ${dbRoll==='low'?'selected':''}>하한 (비교용)</option><option value="high" ${dbRoll==='high'?'selected':''}>상한 (비교용)</option></select></label><button class="btn primary" data-action="equip-db" data-id="${esc(id)}">장착 · 자동 반영</button></div><div class="auto-stats">${dbStatsList(m.stats)}</div>${item.boosts?.length?`<h4>스킬 보너스</h4>${item.boosts.map(b=>`<div class="small">${esc(b.name)} <b>+${b.level}</b></div>`).join('')}<p class="hint">자동 모드: 최종 스킬 레벨과 계수에 연결</p>`:''}${item.set?'<p class="hint">세트 장비 · 자동 모드에서 조각 수별 보너스 적용</p>':''}<details><summary>기본 파서 외 항목 ${m.unapplied.length}개 · 자동 적용 여부는 검증 탭</summary><p class="tiny code-wrap">${esc(item.id)}</p>${m.unapplied.map(u=>`<p class="tiny muted">${esc(u.name||'')} ${esc(u.stat||'')} ${fmt(u.value??u.min??0,2)} / ${esc(u.reason)}</p>`).join('')}</details><a class="small" href="https://www.grimtools.com/db/ko/search?query=${encodeURIComponent(item.en)}&in_description=1&exact_match=0" target="_blank" rel="noopener noreferrer">그림툴에서 이름 검색 ↗</a>`;
 document.querySelectorAll('.db-card').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));
}
function installDb(item,target,roll='mean'){
 const m=CATALOG.mapped(item,roll);const p={name:item.name,enabled:true,stats:m.stats,db:{id:item.id,en:item.en,gameVersion:CATALOG.DB.data.meta.gameVersion,type:item.type,rarity:item.rarity,level:item.level,roll,boosts:item.boosts,modifiers:m.modifiers,unapplied:m.unapplied,raw:item.raw,conversions:item.conversions,set:item.set,requirements:item.requirements}};
 const e=state.equipment[target.slot];e.parts[target.part]=p;e.reviewed=!!e.parts.item.db;
 if(target.part==='item'){for(const k of ['component','augment']){const old=e.parts[k]?.db&&CATALOG.DB.get(e.parts[k].db.id);if(old&&!CATALOG.compatible(old,target.slot,k,p.db))e.parts[k]=DATA.blankPart();}}
 if(target.part==='item'&&/legendary|epic/i.test(item.rarity||'')){e.parts.prefix=DATA.blankPart();e.parts.suffix=DATA.blankPart();}
 state.meta.dbImported=true;state.meta.gameVersion=CATALOG.DB.data.meta.gameVersion;
}
function autoTemplate(){if(CATALOG.DB.phase!=='ready'){toast('DB가 준비된 뒤 사용하세요.');return;}if(!confirm('현재 장비를 서약운반자 목록으로 바꿉니다. 실제 DB에서 확인되는 본체·부품·증강제를 자동 장착합니다. 기존 빌드는 먼저 JSON으로 저장하세요.'))return;
 state=DATA.state(false);state.auto=AUTO.defaults();state.combat.darWD=210;state.combat.skillConversion={};state.meta.note='장비 DB 자동 구성. 스킬 계수·동작 시간은 예제 참조값입니다. 장비 외 능력치와 버프를 별도로 확인하세요.';
 let found=0,missing=[],ambiguous=[];for(const [sid,,ko,en]of SLOTS){for(const p of ['item','component','augment']){const name=p==='item'?ko:state.equipment[sid].parts[p].name;if(!name)continue;const base=state.equipment[sid].parts.item.db;
  const needles=[name,p==='item'?en:''].filter(Boolean).map(CATALOG.clean);
  const rows=CATALOG.DB.search('',sid,p,base,{limit:100000}).rows.filter(x=>needles.some(n=>CATALOG.clean(x.name)===n||CATALOG.clean(x.en)===n));
  if(!rows.length){missing.push(`${SLOTS.find(x=>x[0]===sid)[1]}: ${name}`);continue;}
  const top=rows[0];if(rows.some(x=>x.id!==top.id&&x.level===top.level)){ambiguous.push(`${SLOTS.find(x=>x[0]===sid)[1]}: ${name}`);continue;}
  installDb(top,{slot:sid,part:p});found++;
 }}if(CATALOG.DB.data.automation){missing.push(...AUTOUI.preset(state));}tab='gear';slot='main';part='item';render();openModal('서약운반자 DB 자동 구성 결과',`<p><b>${found}개 항목</b>의 이름과 실제 옵션을 가져왔습니다.</p><div class="notice info">접두·접미사는 부위별 변형을 직접 선택하세요. 능력치·스킬·적 조건까지 완성된 실측 캐릭터는 아닙니다.</div>${missing.length?`<h3>찾지 못한 항목 ${missing.length}</h3>${missing.map(x=>`<p class="small">${esc(x)}</p>`).join('')}`:''}${ambiguous.length?`<h3>동일 단계 중복 · 선택 필요</h3>${ambiguous.map(x=>`<p class="small">${esc(x)}</p>`).join('')}`:''}<button class="btn primary" data-action="close-modal">확인</button>`);
}
async function portable(){if(state.auto?.enabled){await AUTOUI.offline();return;}try{if(CATALOG.DB.phase!=='ready')return;if(location.protocol==='file:'){toast('현재 파일은 이미 DB 포함 오프라인 HTML입니다. 현재 빌드는 JSON으로 저장하세요.');return;}
 const response=await fetch('/api/portable');if(!response.ok)throw new Error('오프라인 HTML 생성에 실패했습니다.');let text=await response.text();const build=JSON.stringify(state).replace(/</g,'\\u003c');text=text.replace('<!-- EMBEDDED_BUILD -->','<script id="embedded-build" type="application/json">'+build+'</scr'+'ipt>');download('Grim_DPS_Lab_Offline.html',text,'text/html;charset=utf-8');toast('아이템 DB와 현재 빌드가 포함된 HTML을 저장했습니다.');}catch(e){toast(e.message);}}
function dbHelp(){openModal('v3 데이터 연결과 지원 범위',`<p>ZIP을 모두 풀고 <b>START_WINDOWS.cmd</b>를 실행합니다. 첫 실행에는 공개 원시 데이터와 실행 환경 다운로드가 필요합니다. 실제 Windows 첫 실행은 이 배포를 만든 환경에서 검증하지 못했습니다.</p><p>장비·접사·부품·증강제 숫자, 전체 스킬/숙련도 목록의 원시 레벨 배열, 장비의 스킬 보너스, 별자리 선택 효과, 세트 임계치가 연결됩니다. 데이터 스냅샷은 화면에 표시되며 최신 게임 패치를 자동으로 가정하지 않습니다.</p><p><b>모든 스킬의 실제 동작이 구현된 것은 아닙니다.</b> 소환/변신 AI, 카덴스·충전·추가 폭발·채널링의 특수 규칙, 정확한 애니메이션 및 시드·승천 적법성은 제외 또는 근사입니다. 검증·출처 탭에서 각 누락을 확인하세요.</p><p>그림툴 URL 및 게임 저장 파일은 직접 불러오지 않습니다. 공개 DB 검색으로 구현했으며 사용자 빌드·로그를 외부에 전송하지 않습니다.</p><p>DB 준비 후 <b>DB 포함 HTML 저장</b>을 사용하면 데이터와 빌드를 함께 보관합니다. 전체 DB 실제 다운로드 및 네이티브 Windows 실행 검증은 TEST_REPORT_KO.md에 별도 표기했습니다.</p><pre class="code code-wrap tiny">${esc(CATALOG.DB.error||'현재 연결 오류 없음')}</pre><div class="row"><button class="btn" data-action="db-retry">연결 다시 확인</button><button class="btn primary" data-action="close-modal">닫기</button></div>`);}

function download(name,text,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function filePick(kind){const inp=document.createElement('input');inp.type='file';inp.accept=kind==='build'?'.json':'.json,.csv';inp.onchange=async()=>{try{const f=inp.files[0];if(!f)return;if(f.size>(kind==='build'?2000000:20000000))throw new Error('파일이 너무 큽니다. 빌드 2MB / 로그 20MB 이하만 허용합니다.');const text=await f.text();if(kind==='build'){const s=validateState(JSON.parse(text));state=s;slot='main';part='item';render();toast('빌드를 불러왔습니다.');}else{let arrays;if(f.name.toLowerCase().endsWith('.csv'))arrays=[{path:'CSV',rows:GD.parseCSV(text)}];else arrays=GD.findArrays(JSON.parse(text));if(!arrays.length)throw new Error('피해 이벤트 객체 배열이 없습니다. 시간과 피해가 있는 JSON/CSV가 필요합니다.');if(arrays.some(a=>a.rows.length>100000))throw new Error('최대 100,000행까지 지원합니다. 측정 구간을 나누어 주세요.');logData={...logData,arrays,arrayIndex:0,rows:arrays[0].rows,fileName:f.name,events:[],sample:false,mitigation:'unknown'};guessMapping();tab='logs';render();}}catch(e){toast(e.message);}};inp.click();}
function guessMapping(){const fs=Object.keys(GD.flatten(logData.rows[0]||{}));const find=re=>fs.find(f=>re.test(f))||'';logData.map={...logData.map,time:find(/(^|\.)(time|timestamp|elapsed|t|timeMs|timestampMs)$/i),damage:find(/(^|\.)(damage|amount|value|damageAmount|totalDamage)$/i),skill:find(/(^|\.)(skill|skillName|ability)$/i),source:find(/(^|\.)(source|attacker|sourceName)$/i),target:find(/(^|\.)(target|targetName|defender)$/i)};if(/ms$/i.test(logData.map.time))logData.map.unit='ms';}
function demoLog(){const d=state.auto?.enabled?{events:Array.from({length:240},(_,i)=>({time:(i+1)/4,damage:GD.calculate(state).total/4,skill:'자동 모델 평균값 시각화',target:'가정 단일 대상',source:'model'}))}:GD.simulate(state,60,73);logData={...logData,arrays:[{path:'events',rows:d.events}],arrayIndex:0,rows:d.events,events:d.events,fileName:'앱에서 생성한 모의 기록',sample:true,mitigation:'after',map:{time:'time',damage:'damage',skill:'skill',target:'target',source:'source',unit:'s',relative:false},start:0,end:60,window:5,filterSource:'all',filterTarget:'all',skipped:0};tab='logs';render();}
function logMapApply(){try{const m=GD.mapEvents(logData.rows,logData.map);logData.events=m.events;logData.skipped=m.skipped;logData.start=0;logData.end=Math.max(1,Math.ceil(m.events.reduce((x,e)=>Math.max(x,e.time),0)+.5));logData.filterSource='all';logData.filterTarget='all';render();toast('매핑 완료. 실제 전투 종료 시간을 확인하세요.');}catch(e){toast(e.message);}}
function scheduleUpdate(){clearTimeout(timer);timer=setTimeout(()=>{updateMetrics();renderAside();persist();if(tab==='analysis'&&!state.auto?.enabled)renderAnalysisDynamic();},200);}
document.addEventListener('input',e=>{
 const el=e.target;
 if(el.id==='library-search'){dbPage=0;renderLibrary(el.value);return;}
 if(el.dataset.bind){const path=el.dataset.bind;if(el.type==='number'){if(el.value===''||!Number.isFinite(Number(el.value)))return;let value=Number(el.value);if(el.min!=='')value=Math.max(Number(el.min),value);if(el.max!=='')value=Math.min(Number(el.max),value);set(path,value);}else if(el.type!=='checkbox'&&el.tagName!=='SELECT')set(path,el.value);scheduleUpdate();}
});
document.addEventListener('change',e=>{
 const el=e.target;
 if(el.id==='db-rarity'){dbRarity=el.value;dbPage=0;renderLibrary($('#library-search').value);return;}
 if(el.id==='db-level'){dbMax=GD.clamp(el.value,1,200);dbPage=0;renderLibrary($('#library-search').value);return;}
 if(el.id==='db-roll'){dbRoll=el.value;renderDbDetail(dbSelected);return;}
 if(el.dataset.bind){if(el.type==='checkbox')set(el.dataset.bind,el.checked);else if(el.tagName==='SELECT')set(el.dataset.bind,el.value);else if(el.type==='number'){let v=GD.n(el.value);if(el.min!=='')v=Math.max(Number(el.min),v);if(el.max!=='')v=Math.min(Number(el.max),v);set(el.dataset.bind,v);el.value=v;}
 if(el.type==='checkbox'||el.tagName==='SELECT'){clearTimeout(timer);render();}else scheduleUpdate();}
 if(el.dataset.logmap){const k=el.dataset.logmap;logData.map[k]=el.type==='checkbox'?el.checked:el.value;}
 if(el.dataset.log){const k=el.dataset.log;if(k==='arrayPath'){logData.arrayIndex=Number(el.value);logData.rows=logData.arrays[logData.arrayIndex].rows;guessMapping();render();}else{logData[k]=el.type==='number'?Number(el.value):el.value;renderLogAnalysis();}}
});
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,i=Number(b.dataset.index);try{
 if(a==='db-help')dbHelp();
 else if(a==='db-retry'){closeModal();fetch('/api/retry',{method:'POST',headers:{'X-Grim-Lab':'1'}}).then(()=>CATALOG.DB.load()).catch(e=>toast(e.message));}
 else if(a==='portable')portable();
 else if(a==='pick-db')renderDbDetail(b.dataset.id);
 else if(a==='db-page'){dbPage=Math.max(0,dbPage+Number(b.dataset.dir));renderLibrary($('#library-search').value);}
 else if(a==='source-db'){const p=state.equipment[slot].parts[part];openModal('가져온 원본 레코드',`<pre class="code code-wrap">${esc(JSON.stringify(p.db,null,2))}</pre>`);}
 else if(a==='reroll-db'){const p=state.equipment[slot].parts[part];const item=CATALOG.DB.get(p.db?.id);if(!item)throw new Error('DB를 준비한 뒤 롤을 변경하세요.');installDb(item,{slot,part},b.dataset.roll);render();}
 else if(a==='equip-db'){
  const item=CATALOG.DB.get(b.dataset.id);if(!item)throw new Error('아이템을 찾을 수 없습니다.');const dest=libraryTarget||{slot,part};
  if(state.meta.demo){if(!confirm('실제 장비를 장착하기 위해 데모 장비와 가정 능력치를 지웁니다. 계속할까요?'))return;state=DATA.state(false);for(const e of Object.values(state.equipment))for(const k of Object.keys(e.parts))e.parts[k]=DATA.blankPart();state.combat.darWD=210;state.combat.skillConversion={};}
  installDb(item,dest,dbRoll);closeModal();render();toast('DB 옵션을 자동 적용했습니다.');
 }
 else if(a==='tab'){tab=b.dataset.tab;render();}
 else if(a==='slot'){slot=b.dataset.slot;part='item';render();}
 else if(a==='part'){part=b.dataset.part;render();}
 else if(a==='close-modal')closeModal();
 else if(a==='template')autoTemplate();
 else if(a==='demo'){if(confirm('현재 변경사항을 바꿉니다. 필요한 내용은 JSON으로 저장하셨나요?')){state=DATA.state(a==='demo');tab='gear';slot='main';part='item';render();}}
 else if(a==='snapshot'){savedA=GD.copy(state);render();toast('현재 장비·전투 조건을 A로 저장했습니다.');}
 else if(a==='restore-a'&&savedA){state=GD.copy(savedA);render();toast('A 기준을 복원했습니다.');}
 else if(a==='clear-a'){savedA=null;render();}
 else if(a==='export-build')download('grim-dps-build.json',JSON.stringify(state,null,2));
 else if(a==='import-build')filePick('build');
 else if(a==='library')libraryModal();
 else if(a==='equip-library'){
  const item=[...customLibrary,...DATA.LIBRARY].find(x=>x.id===b.dataset.id);if(item){const target=libraryTarget||{slot,part};state.equipment[target.slot].parts[target.part]={name:item.name,enabled:true,stats:GD.copy(item.stats||{})};state.equipment[target.slot].reviewed=false;closeModal();render();toast(Object.keys(item.stats||{}).length?'참조 수치를 적용했습니다. 실제 옵션을 확인하세요.':'이름을 적용했습니다. 장비 수치를 입력하세요.');}
 }
 else if(a==='import-library'){
  const inp=document.createElement('input');inp.type='file';inp.accept='.json';inp.onchange=async()=>{try{const f=inp.files[0];if(!f)return;if(f.size>2000000)throw new Error('아이템 JSON은 2MB 이하로 준비하세요.');const j=JSON.parse(await f.text());const arr=Array.isArray(j)?j:j.items;if(!Array.isArray(arr)||arr.length>500)throw new Error('items 배열(최대 500개)이 필요합니다.');const allowed=new Set(Object.keys(FIELD_LABELS));let added=0;for(const x of arr){if(!x||typeof x.name!=='string'||!PARTS.some(p=>p[0]===x.part)||!x.stats||typeof x.stats!=='object')throw new Error('name, part, stats가 있는 아이템 목록이 필요합니다.');const stats={};for(const[k,v]of Object.entries(x.stats)){if(!allowed.has(k))throw new Error('지원하지 않는 스탯: '+k);if(!Number.isFinite(Number(v))||Math.abs(Number(v))>1e8)throw new Error('잘못된 수치: '+k);stats[k]=Number(v);}x._clean={name:x.name.slice(0,200),part:x.part,stats,slots:Array.isArray(x.slots)?x.slots.filter(v=>SLOTS.some(s=>s[0]===v)):[],status:'사용자 가져온 수치'};}
   for(const x of arr){const old=customLibrary.find(v=>v.name===x._clean.name&&v.part===x._clean.part);if(old)Object.assign(old,x._clean);else customLibrary.push({id:'user-'+Date.now()+'-'+added,...x._clean});added++;}customLibrary=customLibrary.slice(-500);persist();renderLibrary($('#library-search')?.value||'');toast(added+'개 항목을 가져왔습니다.');}catch(e){toast(e.message);}};inp.click();
 }
 else if(a==='export-library')download('grim-dps-items.json',JSON.stringify({schema:'grim-dps-items/v1',items:customLibrary},null,2));
 else if(a==='save-item'){
  const p=state.equipment[slot].parts[part];if(!p.name.trim())throw new Error('이름을 먼저 입력하세요.');
  const exists=customLibrary.find(x=>x.name===p.name&&x.part===part);const obj={id:exists?.id||'user-'+Date.now(),name:p.name,part,slots:[],stats:GD.copy(p.stats),status:'사용자 저장 수치'};if(exists)Object.assign(exists,obj);else customLibrary.push(obj);persist();toast('개인 라이브러리에 저장했습니다.');
 }
 else if(a==='clear-part'){state.equipment[slot].parts[part]=DATA.blankPart();state.equipment[slot].reviewed=false;render();}
 else if(a==='paste-tooltip')openModal('장비 툴팁 붙여넣기',`<div class="note-block">영문/한글의 주요 고정 피해·피해 증가·공격 능력·속도 등을 인식합니다. <strong>기본 아이템 옵션만</strong> 붙여넣으세요. 발동 스킬 설명이나 +스킬 레벨은 자동 해석하지 않습니다.</div><textarea id="tooltip-text" rows="10" placeholder="예: 10 Piercing Damage&#10;+50% Piercing Damage&#10;70 Defensive Ability" style="margin-top:14px"></textarea><div class="row" style="margin-top:12px"><button class="btn primary" data-action="parse-tooltip">인식 결과 확인</button></div><div id="tooltip-preview"></div>`);
 else if(a==='parse-tooltip'){tooltipPreview=GD.parseTooltip($('#tooltip-text').value);$('#tooltip-preview').innerHTML=`<div class="inline-message">${tooltipPreview.recognized.length}줄 인식 · ${tooltipPreview.unknown.length}줄 미반영</div><table><thead><tr><th>적용할 항목</th><th>값</th></tr></thead><tbody>${Object.entries(tooltipPreview.stats).map(([k,v])=>`<tr><td>${esc(FIELD_LABELS[k]||k)}</td><td>${fmt(v,2)}</td></tr>`).join('')}</tbody></table>${tooltipPreview.unknown.length?`<details><summary>자동 적용하지 않는 줄</summary><pre class="code">${esc(tooltipPreview.unknown.join('\n'))}</pre></details>`:''}<div class="hint">이 결과로 현재 항목의 숫자를 교체합니다. 누락·잘못 인식한 수치를 직접 고쳐주세요.</div><button class="btn primary" data-action="apply-tooltip" ${!tooltipPreview.recognized.length?'disabled':''}>확인 · 현재 항목에 적용</button>`;}
 else if(a==='apply-tooltip'&&tooltipPreview){state.equipment[slot].parts[part].stats=GD.copy(tooltipPreview.stats);state.equipment[slot].reviewed=false;closeModal();render();}
 else if(a==='add-buff'){state.buffs.push({name:'추가 버프',enabled:true,stats:{}});render();}
 else if(a==='delete-buff'){state.buffs.splice(i,1);render();}
 else if(a==='add-wps'){if(state.wps.length>=20)throw new Error('발동 사격은 최대 20개입니다.');state.wps.push({id:'custom-'+Date.now(),name:'새 발동 사격',enabled:true,chance:0,wd:100,hitsMain:1,hitsOff:1,cycleMs:400,flat:{},conversion:{}});render();}
 else if(a==='delete-wps'){state.wps.splice(i,1);render();}
 else if(a==='add-extra'){state.extras.push({id:'extra-'+Date.now(),name:'출혈 (유지 DPS 직접 입력)',enabled:true,kind:'dot',type:'bleed',group:'weapon-bleed',rate:0,uptime:100,afterMitigation:false});render();}
 else if(a==='delete-extra'){state.extras.splice(i,1);render();}
 else if(a==='add-rr'){state.target.rr.push({id:'rr-'+Date.now(),name:'새 저항 감소',group:'effect-'+Date.now(),type:'pierce',kind:'stack',value:0,enabled:true});render();}
 else if(a==='delete-rr'){state.target.rr.splice(i,1);render();}
 else if(a==='edit-meta')openModal('빌드 정보',`${field('빌드 이름','meta.name',{type:'text'})}<div style="margin-top:12px">${field('게임 버전 / 데이터 기준','meta.gameVersion',{type:'text'})}</div><div style="margin-top:12px">${field('메모','meta.note',{type:'text'})}</div><div style="margin:15px 0">${check('작동 예제 · 실제 장비 미검증 표시','meta.demo')}</div><button class="btn primary" data-action="close-meta">확인</button>`);
 else if(a==='close-meta'){closeModal();render();}
 else if(a==='import-log')filePick('log');
 else if(a==='sample-log'||a==='simulation-log')demoLog();
 else if(a==='apply-log')logMapApply();
 else if(a==='export-log'){const rows=logData.events.filter(e=>(logData.filterSource==='all'||e.source===logData.filterSource)&&(logData.filterTarget==='all'||e.target===logData.filterTarget)&&e.time>=logData.start&&e.time<=logData.end);const csv=['time,damage,skill,target,source',...rows.map(e=>[e.time,e.damage,e.skill,e.target,e.source].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\n');download('filtered-damage.csv','\uFEFF'+csv,'text/csv;charset=utf-8');}
 else if(a==='log-schema')openModal('입력 예시 · 앱 공통 이벤트 형식',`<p class="small muted">DPYes 원본 스키마라고 주장하는 형식이 아닙니다. 원본의 필드를 이 의미에 맞춰 매핑합니다. 기록당 시간과 피해량이 필요합니다.</p><pre class="code">${esc(JSON.stringify({events:[{time:0.4,damage:12500,skill:'폭풍 분사',target:'대상 A',source:'player'},{time:0.8,damage:19000,skill:'냉각성 탄환',target:'대상 A',source:'player'}]},null,2))}</pre><div class="hint">이벤트 파일과 별개로, 실제 전투 시작·종료 시간을 입력해야 전체 평균이 정확해집니다.</div>`);
 }catch(err){console.error(err);toast(err.message||'입력을 확인하세요.');}
});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='Tab'&&$('.modal')){const f=[...$('.modal').querySelectorAll('button,input,select,textarea,a')].filter(e=>!e.disabled);const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
loadLocal();try{const seed=$('#embedded-build');if(seed)state=validateState(JSON.parse(seed.textContent));}catch(e){console.warn(e);}render();
CATALOG.DB.on(()=>{if(CATALOG.DB.phase==='ready'){render();}const node=$('#db-status');if(node)node.innerHTML=dbStatus();if($('#library-results'))renderLibrary($('#library-search')?.value||'');});
CATALOG.DB.load();
AUTOUI.install();
window.LAB={getState:()=>GD.copy(state),installDb:(id,slot,part)=>{installDb(CATALOG.DB.get(id),{slot,part});render();},setState:s=>{state=validateState(s);render();},getResult:()=>GD.calculate(state),getLog:()=>GD.copy(logData),render};
})();
