/* Automatic skill/devotion editor. All imported content is escaped; only JSON
 * records are read. Missing raw data is displayed, never patched with a fake DB. */
(function(root){'use strict';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f=(v,d=0)=>Number.isFinite(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:d}):'—';
const kind={dar:'기본 공격 대체',wps:'발동 공격',attack:'사용 공격 / 약화',buff:'버프 / 지속 효과',area:'장판 버프',aura:'공격 오라',pet:'소환·변신 — 피해 제외',special:'특수 순서 — 피해 제외',unknown:'실행 형태 미확인',modifier:'연결 강화'};
const labels={physique:'체격',cunning:'교활',spirit:'정신',oa:'공격 능력',da:'방어 능력',hp:'체력',oaPct:'공격 능력 +%',daPct:'방어 능력 +%',hpPct:'체력 +%',crit:'치명타 피해 +%p',attackSpeed:'공격 속도 +%p',castSpeed:'시전 속도 +%p',moveSpeed:'이동 속도 +%p',armor:'방어구',armorPct:'방어구 +%',armorAbsorbPct:'방어구 흡수 증가',incAll:'모든 피해 +%',incElemental:'원소 피해 +%',allSkills:'모든 스킬 +',leech:'공격 피해 체력 전환',healingPct:'회복 효과 +%',enemyDamageReduction:'적 피해 감소'};
const types={physical:'물리',pierce:'관통',fire:'화염',cold:'냉기',lightning:'번개',acid:'산성',vitality:'생명력',aether:'에테르',chaos:'카오스',elemental:'원소',trauma:'내부 출혈',bleed:'출혈',burn:'화상',frostburn:'동상',electrocute:'감전',poison:'중독',decay:'생명력 부패'};
function statName(k){if(labels[k])return labels[k];const m=/^(flat|inc|duration|res|maxRes)_(.+)$/.exec(k);if(m)return (types[m[2]]||m[2])+({flat:' 추가 피해',inc:' 피해 +%',duration:' 지속시간',res:' 저항',maxRes:' 최대 저항 +%p'}[m[1]]);return k;}
const panel=(title,sub,body)=>`<section class="panel auto-panel"><div class="panel-head"><div><h2>${e(title)}</h2><p class="panel-sub">${e(sub)}</p></div></div><div class="panel-body">${body}</div></section>`;
const input=(label,op,key,value,step=1,min=0,max=100)=>`<label class="field">${e(label)}<input type="number" data-a-op="${op}" data-a-key="${e(key)}" value="${e(value)}" step="${step}" min="${min}" max="${max}"></label>`;
const btn=(text,op,key='',cls='')=>`<button class="btn ${cls}" data-a-op="${op}" data-a-key="${e(key)}">${e(text)}</button>`;
function tableStats(raw){return `<dl class="auto-stat-grid">${Object.entries(raw).filter(([,v])=>typeof v==='number'&&v!==0).map(([k,v])=>`<div><dt>${e(statName(root.AUTO.mappedKey(k)||k))}</dt><dd>${f(v,3)}</dd></div>`).join('')}</dl>`;}
function getDB(){return root.CATALOG.DB.data?.automation;}
function wait(){return panel('자동 계산 데이터 연결','아이템 DB + 정확한 스킬 레벨 배열 + 별자리 그래프',`<div class="notice info"><div><strong>v3 DB를 준비하고 있습니다.</strong><p>START_WINDOWS.cmd로 실행하면 공개 DB를 내려받습니다. 레벨 1·최대·최종 최대만 있는 표를 중간 레벨로 보간하지 않습니다.</p><p>다운로드 실패나 데이터 버전 불일치 시 임의의 데이터로 대신하지 않습니다.</p></div></div>`);}
function toolbar(state){return `<div class="auto-toolbar"><div><b>BUILD COMPILER</b><span>장비 → 스킬 레벨 → 별자리 → 피해 기대값</span></div>${btn('서약운반자 스킬·별자리 적용','preset','','primary')}${btn('자동 배분 초기화','reset-auto')}</div><div class="auto-legend">전체 DB 항목을 탐색합니다. 수치가 연결되어도 펫 AI·특수 공격 패턴 등 미지원 효과는 포함되지 않습니다. <b>‘검증·출처’ 탭의 제외 항목을 확인하세요.</b></div>`;}
function character(state,r){const d=getDB();if(!d)return wait();const a=root.AUTO.config(state),c=r.autoReport;return toolbar(state)+panel('캐릭터와 직업','배분 포인트를 바꾸면 장비 요구치와 파생 능력치도 다시 계산합니다.',`<div class="field-grid">${input('캐릭터 레벨','top','level',a.level,1,1,100)}${input('사용 가능한 스킬 포인트','top','skillBudget',a.skillBudget,1,0,300)}${input('사용 가능한 능력치 포인트','top','attributeBudget',a.attributeBudget,1,0,200)}</div><div class="auto-masteries">${d.masteries.map(m=>`<article class="mastery-box ${a.masteries[m.id]?'selected':''}"><h3>${e(m.name)}</h3><small>${e(m.en)}</small>${input('숙련도','mastery',m.id,a.masteries[m.id]||0,1,0,m.max)}</article>`).join('')}</div><div class="notice info">두 직업까지 선택 가능합니다. 캐릭터 레벨과 퀘스트 완료 상황은 사용자 선택이며, 스킬·능력치 예산을 초과하면 경고합니다.</div>`)+panel('체격 · 교활 · 정신','장비 수치, 숙련도, 별자리, 스킬의 능력치 보너스를 자동 합산합니다.',`<div class="field-grid">${['physique','cunning','spirit'].map(k=>input(labels[k]+' 투자 포인트','attr',k,a.attributes[k],1,0,200)).join('')}</div><div class="auto-numbers">${['physique','cunning','spirit','oa','da','hp'].map(k=>`<div><small>${e(labels[k])}</small><strong>${f(c?.a?.[k],1)}</strong></div>`).join('')}</div><div class="notice">플레이어 성장식이 원본에서 확정되지 않은 부분은 <b>공개 가이드의 참고 프로필</b>을 사용합니다. 인게임 정밀 능력치 검증은 아직 이루어지지 않았습니다.</div><details><summary>고급 · 검증된 기초 성장값으로 보정</summary><p class="hint">장비·능력치 투자·스킬을 제외한 레벨 기본값입니다. 캐릭터 창 최종 OA/DA를 넣으면 중복 계산됩니다. 빈 값은 참고 프로필을 사용합니다.</p><div class="field-grid">${['baseOA','baseDA','baseHP'].map(k=>input(k,'profile',k,a.profile[k]??'',.1,0,20000)).join('')}</div></details>`);}
function skillView(state,r){const d=getDB();if(!d)return wait();const a=root.AUTO.config(state),c=r.autoReport,chosen=d.masteries.filter(m=>a.masteries[m.id]>0),all=c?.skills||[];return toolbar(state)+panel('스킬 배분과 장비 보너스',`${c?.spent||0} / ${a.skillBudget} 포인트 · ${d.skills.length}개 DB 스킬 · 중간 레벨도 원시 배열에서 계산`,`${chosen.length?'':`<div class="notice">먼저 ‘캐릭터’에서 두 직업을 선택하거나 서약운반자 배분을 적용하세요.</div>`}<div class="row"><label class="field grow">스킬 검색<input type="search" id="auto-skill-search" placeholder="한글 / 영어 / 레코드 검색"></label><label class="check"><input type="checkbox" data-a-op="condition" data-a-key="inSeal" ${a.conditions.inSeal?'checked':''}>표식 등 장판 버프 위</label><label class="check"><input type="checkbox" data-a-op="condition" data-a-key="lowHealth" ${a.conditions.lowHealth?'checked':''}>저체력 조건</label><label class="check"><input type="checkbox" data-a-op="condition" data-a-key="onHit" ${a.conditions.onHit?'checked':''}>피격·처치 발동 근사</label></div>${chosen.map(m=>`<div class="auto-mastery-title"><h3>${e(m.name)}</h3><span>숙련도 ${a.masteries[m.id]}</span></div><div class="auto-skill-list">${d.skills.filter(s=>s.mastery===m.id).sort((x,y)=>(x.y||0)-(y.y||0)||(x.x||0)-(y.x||0)).map(s=>{const info=all.find(x=>x.id===s.id),lev=info?.level||0,p=N(a.points[s.id]);return `<article class="auto-skill ${p?'learned':''} ${s.kind==='base'?'':'child'}" data-search="${e((s.name+' '+s.en+' '+s.id).toLowerCase())}"><div class="skill-top"><div><strong>${e(s.name)}</strong><small>${e(s.en)} · ${e(kind[info?.role]||s.kind)}</small></div><span class="rank-pill">${lev}<small> / ${s.ultimate}</small></span></div><div class="skill-controls">${input('직접 투자','point',s.id,p,1,0,s.max)}<div class="level-detail">장비 보너스 <b>+${info?.bonus||0}</b><span>기본 상한 ${s.max} · 최종 ${s.ultimate}</span></div>${s.kind==='base'?`<label class="check"><input type="checkbox" data-a-op="enabled" data-a-key="${e(s.id)}" ${a.disabled[s.id]!==true?'checked':''}>사용</label>`:''}${s.kind==='base'?btn(a.primary===s.id?'주력 선택됨':'주력 공격','primary',s.id,a.primary===s.id?'primary small':'small'):''}</div>${p?`<details><summary>레벨 ${lev}의 실제 데이터 · 적용 범위</summary>${tableStats(info?.raw||{})}<p class="tiny muted">${e(s.id)} · ${e(s.rankSource)}</p><div class="field-grid"><label class="field">실행 형태 (자동 분류 재검토용)<select data-a-op="role" data-a-key="${e(s.id)}"><option value="">자동 분류</option>${Object.entries(kind).filter(([k])=>k!=='modifier').map(([k,v])=>`<option value="${k}" ${a.rotation[s.id]?.role===k?'selected':''}>${e(v)}</option>`).join('')}</select></label>${input('보조 공격 재시전 간격, 초 (0=자동)','interval',s.id,a.rotation[s.id]?.interval||0,.1,0,180)}${input('200% 속도 동작 길이, ms (0=추정)','cycleMs',s.id,a.rotation[s.id]?.cycleMs||0,1,0,3000)}</div><p class="hint">실행 형태를 강제 변경해도 미지원 펫 AI나 특수 스킬 규칙이 구현되는 것은 아닙니다.</p></details>`:''}</article>`;}).join('')}</div>`).join('')}`);}
function N(v){return root.AUTO.N(v);}
function starMap(c,pick){const xs=c.stars.map(s=>N(s.position?.x)),ys=c.stars.map(s=>N(s.position?.y));const minX=Math.min(...xs),minY=Math.min(...ys),w=Math.max(1,Math.max(...xs)-minX),h=Math.max(1,Math.max(...ys)-minY);const pt=s=>({x:25+(N(s.position?.x)-minX)/w*220,y:22+(N(s.position?.y)-minY)/h*150});return `<svg class="constellation" viewBox="0 0 270 195" role="group" aria-label="${e(c.name)} 별 선택">${c.stars.flatMap(s=>(s.predecessors||[]).map(p=>{const prev=c.stars.find(x=>x.index===p);if(!prev)return '';const a=pt(prev),b=pt(s);return `<path class="star-edge ${pick.includes(p)&&pick.includes(s.index)?'on':''}" d="M${a.x} ${a.y}L${b.x} ${b.y}"/>`;})).join('')}${c.stars.map(s=>{const a=pt(s);return `<g class="star-node ${pick.includes(s.index)?'on':''} ${s.celestial_power?'power':''}" role="button" tabindex="0" aria-label="${e(c.name)} ${s.index+1}번 별" aria-pressed="${pick.includes(s.index)}" data-a-op="star" data-a-key="${e(c.id)}" data-a-index="${s.index}"><circle cx="${a.x}" cy="${a.y}" r="${s.celestial_power?12:9}"/><text x="${a.x}" y="${a.y+4}" text-anchor="middle">${s.index+1}</text><title>${e(JSON.stringify(s.bonuses))}</title></g>`;}).join('')}</svg>`;}
function devotionView(state,r){const d=getDB();if(!d)return wait();const a=root.AUTO.config(state),c=r.autoReport,learned=c?.bases?.filter(s=>s.enabled)||[];return panel('별자리와 발동 효과',`${c?.dev?.points||0} / 55 포인트 · ${d.devotions.length}개 별자리`, `<div class="affinity-strip">${root.AUTO.AFF.map((x,i)=>`<span class="aff affinity-${i}">${['보라','빨강','초록','노랑','파랑'][i]} <b>${c?.dev?.aff?.[x]||0}</b></span>`).join('')}</div><div class="row"><label class="field grow">별자리 검색<input id="auto-dev-search" type="search" placeholder="한글 / 영어 이름"></label><label class="check"><input id="auto-dev-selected" type="checkbox">투자한 별자리만</label></div><p class="hint">각 별을 눌러 선택합니다. 잘못된 친화도·선행 별·중복 연결은 검증 탭에서 표시합니다. 완성 시 친화도가 지급됩니다. 시작 경로의 실현 가능성까지 보증하지는 않습니다.</p><div class="devotion-grid">${d.devotions.map(c=>{const pick=a.devotions[c.id]||[];return `<article class="dev-card ${pick.length?'selected':''}" data-search="${e((c.name+' '+c.en+' '+c.id).toLowerCase())}" data-picked="${pick.length}"><div class="row between"><h3>${e(c.name)}</h3><b>${pick.length}/${c.stars.length}</b></div><p class="tiny muted">${e(c.en)} · 필요 ${Object.entries(c.affinity_required||{}).map(([k,v])=>`${k} ${v}`).join(' / ')||'없음'}</p>${starMap(c,pick)}<div class="row">${btn('완성','dev-all',c.id,'small')}${btn('해제','dev-clear',c.id,'small ghost')}</div>${c.stars.filter(s=>s.celestial_power).map(s=>{const p=s.celestial_power;return `<div class="power-card"><b>${e(p.name||c.name)}</b>${input('발동 스킬 레벨','power-level',p.dbr,a.powerLevels[p.dbr]??p.level,1,1,p.level)}<label class="field">연결 스킬<select data-a-op="binding" data-a-key="${e(p.dbr)}"><option value="">연결 안 함</option>${learned.map(k=>`<option value="${e(k.id)}" ${a.bindings[p.dbr]===k.id?'selected':''}>${e(k.name)}</option>`).join('')}</select></label><small>${p.rankSource==='raw-arrays'?'정확한 레벨 배열':'원시 레벨 배열 누락'} · ${e(p.proc?.trigger_key||'조건 미확인')}</small></div>`;}).join('')}<details><summary>선택한 별의 옵션</summary>${c.stars.filter(s=>pick.includes(s.index)).map(s=>`<b>별 ${s.index+1}</b>${tableStats(s.bonuses)}`).join('')||'<p class="hint">아직 선택하지 않았습니다.</p>'}</details></article>`;}).join('')}</div>`);}
function targetView(state,r){const a=root.AUTO.config(state);return panel('단일 대상과 전투 조건','적의 기본 저항을 입력합니다. 투자한 스킬·별자리·아이템의 저항 감소는 자동으로 계산합니다.',`<div class="notice info">장비만으로 적의 크기, 실제 명중 탄환 수, 이동 시간을 알 수는 없습니다. 아래 값은 측정 조건이며, ‘장비 옵션’ 입력이 아닙니다.</div><div class="field-grid">${input('적 방어 능력','target','da',a.target.da,1,0,10000)}${input('적 방어구','target','armor',a.target.armor,1,0,50000)}${input('적 방어구 흡수율 %','target','armorAbsorption',a.target.armorAbsorption,1,0,100)}${input('피해 흡수 %','target','absorption',a.target.absorption,1,0,100)}${input('타격당 고정 흡수','target','flatAbsorption',a.target.flatAbsorption,1,0,50000)}${input('회피율 %','target','avoidance',a.target.avoidance,1,0,100)}</div><details open><summary>적 기본 저항</summary><div class="field-grid">${[...root.AUTO.DIRECT,'bleed'].map(t=>input(types[t]+' %','target-res',t,a.target.resists[t]||0,1,-300,300)).join('')}</div></details><h3>공격 실행 조건</h3><div class="field-grid"><label class="field">동작 시간 모델<select data-a-op="timing" data-a-key="mode"><option value="estimated" ${a.timing.mode==='estimated'?'selected':''}>무기 속도 + 스킬별 추정 동작</option><option value="measured" ${a.timing.mode==='measured'?'selected':''}>실측 공격 실행 횟수</option></select></label>${input('실측 공격 실행 횟수 / 초','timing','measuredAPS',a.timing.measuredAPS,.01,.01,20)}${input('전투 중 공격 유지율 %','timing','uptime',a.timing.uptime,1,0,100)}${input('산탄 명중 비율 (1=전부)','timing','projectileHitFraction',a.timing.projectileHitFraction,.05,0,1)}</div><p class="hint">투사체 수는 DB에서 읽되 산탄은 명중 비율을 곱합니다. 애니메이션 추정은 DPYes 실측과 동일하다고 보장하지 않습니다.</p>`);}
function audit(state,r){const d=getDB(),c=r.autoReport;if(!d||!c)return wait();const issues=c.issues||[],sev={error:'수정 필요',warning:'근사 / 제외'};return panel('계산 검증과 적용 범위','자동으로 채워졌다는 것과 게임 엔진을 완전히 재현했다는 것은 다릅니다.',`<div class="auto-numbers"><div><small>포인트</small><strong>${c.spent||0}/${c.auto?.skillBudget||250}</strong></div><div><small>별자리</small><strong>${c.dev?.points||0}/55</strong></div><div><small>유효성</small><strong>${c.valid?'검사 통과':'수정 필요'}</strong></div><div><small>표시된 진단</small><strong>${issues.length}</strong></div></div><div class="notice"><b>${e(r.coverage?.scope||'')}</b><br>Windows 실제 실행 검증: 이 배포의 테스트 보고서를 확인하세요. 미실행 테스트를 통과로 표기하지 않습니다.</div><div class="row">${btn('계산 진단 JSON 저장','export-audit','','primary')}${btn('DB JSON 가져오기','import-db')}${btn('DB 포함 HTML 저장','offline')}</div><div class="audit-list">${issues.map(i=>`<article class="audit-item ${i.severity}"><span class="badge ${i.severity==='error'?'':'gold'}">${sev[i.severity]||i.severity}</span><div><b>${e(i.source)}</b><p>${e(i.message)}</p><small>${e(i.code)}</small></div></article>`).join('')||'<p>표시할 진단이 없습니다.</p>'}</div>`)+panel('합산 경로','장비 / 세트 / 숙련도 / 별자리 / 스킬 효과를 추적합니다.',(c.sources||[]).map(s=>`<details><summary>${e(s.name)} <small>${e(s.source)} ${e(s.slot||'')}</small></summary>${tableStats(Object.fromEntries(Object.entries(s.stats||{})))}</details>`).join(''))+panel('세트와 저항 감소','동일 세트 조각 중복 / 동일 이름 디버프 중복을 구분합니다.',`<pre class="code code-wrap">${e(JSON.stringify({sets:c.gear?.setDetails||[],resistanceReductions:c.rrs||[],metadata:root.CATALOG.DB.data.meta},null,2))}</pre>`);}
function analysis(state,r){const c=r.autoReport;if(!c?.a)return wait();return panel('예상 피해의 구성','소환·특수 스킬 제외 여부는 검증·출처 탭에서 확인하세요.',`<div class="auto-numbers"><div><small>주력 직접 피해</small><strong>${f(r.direct)}</strong></div><div><small>지속·발동·보조 공격</small><strong>${f(r.extra)}</strong></div><div><small>지원분 합계</small><strong>${f(r.total)}</strong></div></div><div class="auto-keyline">${e(r.coverage.scope)} · 유효성 ${r.coverage.valid?'검사 통과':'수정 필요'} · 제외 진단 ${r.coverage.excluded}개</div><div class="scroll-table"><table><thead><tr><th>공격</th><th>선택 비중</th><th>실행당 피해</th><th>동작(초)</th><th>DPS 기여</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${e(x.name)}</td><td>${f(x.p*100,1)}%</td><td>${f(x.damage)}</td><td>${f(x.seconds,3)}</td><td>${f(x.dps)}</td></tr>`).join('')}</tbody></table></div><div class="scroll-table" style="margin-top:18px"><table><thead><tr><th>별도 효과</th><th>분류</th><th>실행 빈도 / 초</th><th>DPS</th></tr></thead><tbody>${r.extras.map(x=>`<tr><td>${e(x.name)}</td><td>${e(x.kind)}</td><td>${f(x.rate,3)}</td><td>${f(x.dps)}</td></tr>`).join('')||'<tr><td colspan="4">계산된 별도 효과 없음</td></tr>'}</tbody></table></div>`)+panel('계산에 사용된 전투 계수','장비 변화가 어느 단계에 반영되는지 확인합니다.',`<div class="auto-numbers"><div><small>공격 실행 / 초</small><strong>${f(r.aps,3)}</strong></div><div><small>명중률</small><strong>${f(r.profile.hit*100,2)}%</strong></div><div><small>치명타 확률</small><strong>${f(r.profile.crit*100,2)}%</strong></div></div><div class="scroll-table"><table><thead><tr><th>피해 유형</th><th>피해 증가</th><th>적 최종 저항(평균)</th><th>기여 DPS</th></tr></thead><tbody>${root.AUTO.ALL.filter(t=>r.types[t]||c.a['inc_'+t]).map(t=>`<tr><td>${e(types[t])}</td><td>+${f(N(c.a['inc_'+t])+N(c.a.incAll),1)}%</td><td>${f(root.AUTO.resistance(c.auto.target,t,c.rrs),1)}%</td><td>${f(r.types[t])}</td></tr>`).join('')}</tbody></table></div><pre class="code">DPS = Σ(공격 선택 확률 × 경감 후 피해) / Σ(확률 × 동작 시간)
      × 사격 유지율 × 보조스킬 시전으로 남은 시간
      + 서로 다른 지속 피해 + 발동 피해
발동 빈도 ≈ λ / (1 + λ × 재사용 대기시간)
유지율 ≈ 1 − exp(−발동 빈도 × 지속시간)</pre><p class="hint">재시전·발동·DoT 유지율은 평균 모델입니다. 전투 이벤트나 DPYes 기록을 예측값으로 맞추는 자동 보정은 하지 않습니다. A/B 비교는 동일한 대상과 조건을 사용하세요.</p>`);}

function help(){return panel('자동 계산 흐름','수치 입력 대신 장비 선택과 포인트 배분을 연결한 베타입니다.',`<p>장비 선택 → 기본/접사/부품 옵션 → 전체·직업·개별 스킬 레벨 → 원시 레벨 배열 → 스킬 강화·변환 → 숙련도·능력치·별자리 → 피해 기대값 순서로 재계산합니다. 같은 옵션을 수동 합계와 중복 적용하지 않습니다.</p><p>데이터에 있는 전체 직업 스킬과 별자리를 탐색하지만, 모든 스킬 동작을 완전히 구현한 게임 엔진은 아닙니다. <b>화면의 DPS는 지원한 효과의 소계</b>입니다. 누락 진단이 있으면 전체 빌드의 정확한 DPS로 취급하면 안 됩니다.</p><div class="scroll-table"><table><thead><tr><th>항목</th><th>처리</th></tr></thead><tbody><tr><td>스킬 레벨</td><td>장비 보너스·상한·선행 그룹, 중간 레벨도 원시 배열</td></tr><tr><td>별자리</td><td>선택 별·친화도·선행 별·발동 레벨·연결, 무기 조건</td></tr><tr><td>세트</td><td>서로 다른 조각 수에 따른 능력치/스킬 변경</td></tr><tr><td>피해</td><td>직접 피해, 기본 공격 대체+발동 사격, 변환, 명중/치명타, 저항·방어구</td></tr><tr><td>근사</td><td>발동 유지율·DoT·시전시간·탄환 명중 수·기초 성장식 일부</td></tr><tr><td>제외/별도 진단</td><td>펫/변신 AI, 특수 주기 공격, 반격, 추가 폭발/파편, 일부 조건부 효과</td></tr></tbody></table></div>`)+panel('전투 계산식','DPYes는 기록계이며 아래는 독립 예측 모델입니다.',`<pre class="code code-wrap">스킬 유효 레벨 = min(최종 상한, 직접 투자 + 전체/직업/개별 장비 보너스)
발동 사격 합계 >100%: 실제 비중 = 해당 확률 / 전체 확률
직접 DPS = Σ(확률 × 경감 후 피해) / Σ(확률 × 동작 시간)
저항: R=(기본저항−서로 다른 -Y% 합)
최종저항=R×(1−sign(R)×max(Z% reduced)/100)−max(X reduced)
발동 빈도 ≈ λ/(1+λ×재사용 대기시간)
평균 유지율 ≈ 1−exp(−발동빈도×지속시간)</pre><p>지속 피해는 공격 횟수마다 무한 누적하지 않습니다. 같은 무기 출처의 경쟁, 별도 스킬 출처와 치명타 스냅샷을 단순화한 모델입니다. 실제 5초 DPYes 최고값과 동일한 결과를 보장하지 않습니다.</p><p>카덴스·충전형·집중형·소환물·추가 폭발과 원시 데이터가 불완전한 효과는 별도 진단을 확인하세요. 장비 시드·승천의 모든 규칙과 스킬 트리의 실제 UI 배치까지 복제하지 않습니다.</p>`)+panel('검증 환경과 데이터','Linux 테스트 결과를 Windows 결과로 표시하지 않습니다.',`<p>이 배포에서 수행한 테스트는 Node/Python 및 Linux Chromium의 합성 표본 검사입니다. 실제 전체 DB 다운로드와 네이티브 Windows 실행은 <b>미검증</b>이며, tests/windows_e2e.py와 GitHub Actions 워크플로를 포함했습니다. Windows 보고서가 not_run이면 성공한 것이 아닙니다.</p><p>공개 데이터: <a href="https://github.com/tednaleid/grimdawn-devotions" target="_blank" rel="noopener">grimdawn-devotions</a> · <a href="https://www.grimdawn.com/guide/gameplay/combat/" target="_blank" rel="noopener">공식 전투 가이드</a> · <a href="https://forums.crateentertainment.com/t/actual-resist-reduction-formula/47174" target="_blank" rel="noopener">저항 감소 실험</a></p><p>출처·상세 처리 범위·검사 기록은 README_KO.md, CALCULATION_SCOPE_KO.md, TEST_REPORT_KO.md에도 포함되어 있습니다.</p>`);}
function preset(state){const d=getDB();if(!d)throw Error('v3 DB가 준비되어야 합니다.');state.auto=root.AUTO.defaults();const a=state.auto,notes=[];
 const findSkill=name=>d.skills.find(s=>clean(s.en)===clean(name)||clean(s.name)===clean(name));
 const plan={'Onslaught':16,'Open Wounds':10,"Amatok's Pact":12,'Bloodfrenzy':8,'Bloodfangs':7,'Bonechilling Cry':12,'Untamed Rage':9,'Battle Surge':1,'Rallying Cry':9,'Frenzied Cry':1,'Impetus':2,'Ranged Expertise':1,'Bursting Round':6,'Chilling Rounds':1,'Storm Spread':10,'Deadly Aim':1,'Word of Renewal':8,'Vigor':6,'Steel Resolve':6,'Inquisitor Seal':12,'Arcane Empowerment':8,'Word of Pain':1,'Word of Agony':1,'Death Sentence':12,'Aura of Conviction':8};
 for(const[name,p]of Object.entries(plan)){const s=findSkill(name);if(!s){notes.push('스킬 미검색: '+name);continue;}a.points[s.id]=Math.min(p,s.max);a.masteries[s.mastery]=/playerclass10/.test(s.mastery)?32:50;if(name==='Onslaught')a.primary=s.id;}
 const names=['Assassin\'s Blade','Toad','Ghoul','Hawk','Hydra','Manticore',"Sailor's Guide",'Empty Throne','Tortoise','Solemn Watcher','Azrakaa, the Eternal Sands'];
 for(const name of names){const c=d.devotions.find(c=>clean(c.en)===clean(name)||clean(c.name)===clean(name));if(c)a.devotions[c.id]=c.stars.map(s=>s.index);else notes.push('별자리 미검색: '+name);}
 for(const color of ['order','ascendant']){const c=d.devotions.find(c=>/crossroad/i.test(c.id+' '+c.en)&&N(c.affinity_bonus?.[color])>0);if(c)a.devotions[c.id]=c.stars.map(s=>s.index);else notes.push('갈림길 미검색: '+color);}
 const bindings={'Assassin\'s Mark':'Onslaught','Acid Spray':'Word of Pain','Shifting Sands':'Storm Spread','Ghoulish Hunger':'Aura of Conviction','Turtle Shell':"Amatok's Pact"};for(const c of d.devotions)for(const s of c.stars)if(s.celestial_power){const p=s.celestial_power,name=bindings[p.en];if(name&&findSkill(name))a.bindings[p.dbr]=findSkill(name).id;}
 state.meta.demo=false;state.meta.name='서약운반자 · 자동 계산';state.meta.note='아이템 DB 스냅샷 '+root.CATALOG.DB.data.meta.gameVersion+' / 미검색 스킬·별자리는 진단 확인';return notes;
}
function clean(s){return String(s||'').toLowerCase().replace(/[^a-z0-9가-힣]/g,'');}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const el=document.createElement('a');el.href=u;el.download=name;el.click();setTimeout(()=>URL.revokeObjectURL(u),3000);}
async function offline(){
 const catalog=root.CATALOG.DB.data;if(!catalog?.automation)throw Error('v3 DB를 준비한 뒤 저장하세요.');
 const clone=document.documentElement.cloneNode(true);
 clone.querySelectorAll('#embedded-build,#embedded-catalog').forEach(x=>x.remove());
 const first=clone.querySelector('script:not([type="application/json"])');if(!first)throw Error('실행 스크립트를 찾지 못했습니다.');
 for(const[id,value]of [['embedded-catalog',catalog],['embedded-build',root.LAB.getState()]]){
  const node=document.createElement('script');node.id=id;node.type='application/json';node.textContent=JSON.stringify(value).replace(/</g,'\\u003c');first.parentNode.insertBefore(node,first);
 }
 clone.querySelector('#modal-root')?.replaceChildren();
 download('Grim_DPS_Lab_v3_Offline.html','<!doctype html>\n'+clone.outerHTML,'text/html;charset=utf-8');
}
function mutate(op,key,value,el){const state=root.LAB.getState();state.auto=root.AUTO.config(state);const a=state.auto;if(['preset','reset-auto'].includes(op)){if(op==='preset'){const notes=preset(state);if(notes.length)alert('DB에서 찾지 못한 항목:\n'+notes.join('\n'));}else state.auto=root.AUTO.defaults();}
 else if(op==='mastery')a.masteries[key]=Math.max(0,Math.floor(N(value)));
 else if(op==='point')a.points[key]=Math.max(0,Math.floor(N(value)));
 else if(op==='primary')a.primary=key;
 else if(op==='attr')a.attributes[key]=Math.max(0,Math.floor(N(value)));
 else if(op==='top')a[key]=N(value);
 else if(op==='condition')a.conditions[key]=!!value;
 else if(op==='enabled')a.disabled[key]=!value;
 else if(op==='timing')a.timing[key]=key==='mode'?value:N(value);
 else if(op==='target')a.target[key]=N(value);
 else if(op==='target-res')a.target.resists[key]=N(value);
 else if(op==='profile'){if(value==='')delete a.profile[key];else a.profile[key]=N(value);}
 else if(['role','interval','cycleMs'].includes(op)){a.rotation[key]??={};a.rotation[key][op]=op==='role'?value:N(value);}
 else if(op==='power-level')a.powerLevels[key]=N(value);
 else if(op==='binding')a.bindings[key]=value;
 else if(op==='star'){const idx=Number(el.dataset.aIndex);const set=new Set(a.devotions[key]||[]);set.has(idx)?set.delete(idx):set.add(idx);a.devotions[key]=[...set];}
 else if(op==='dev-all'){const c=getDB().devotions.find(c=>c.id===key);a.devotions[key]=c.stars.map(s=>s.index);}
 else if(op==='dev-clear')a.devotions[key]=[];
 else if(op==='offline'){offline().catch(e=>alert(e.message));return;}
 else if(op==='export-audit'){const r=root.LAB.getResult();download('grim-dps-v3-diagnostic.json',JSON.stringify({generatedAt:new Date().toISOString(),db:root.CATALOG.DB.data?.meta,total:r.total,direct:r.direct,extra:r.extra,coverage:r.coverage,issues:r.autoReport?.issues,skills:r.autoReport?.skills.map(x=>({id:x.id,hard:x.hard,bonus:x.bonus,level:x.level,role:x.role})),stats:r.a.g},null,2));return;}
 else if(op==='import-db'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{if(input.files[0].size>150e6)throw Error('DB 파일은 150MB 이하');root.CATALOG.DB.accept(JSON.parse(await input.files[0].text()));root.LAB.render();}catch(e){alert(e.message);}};input.click();return;}
 else return;root.LAB.setState(state);
}
function install(){document.addEventListener('change',ev=>{const el=ev.target;if(!el.dataset.aOp)return;try{mutate(el.dataset.aOp,el.dataset.aKey,el.type==='checkbox'?el.checked:el.value,el);}catch(e){alert(e.message);console.error(e);}});document.addEventListener('click',ev=>{const el=ev.target.closest('[data-a-op]');if(!el||el.matches('input,select'))return;try{mutate(el.dataset.aOp,el.dataset.aKey,null,el);}catch(e){alert(e.message);console.error(e);}});document.addEventListener('keydown',ev=>{if(['Enter',' '].includes(ev.key)&&ev.target.matches('.star-node')){ev.preventDefault();ev.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});document.addEventListener('input',ev=>{if(ev.target.id==='auto-skill-search'){const q=ev.target.value.toLowerCase();document.querySelectorAll('.auto-skill').forEach(x=>x.hidden=!x.dataset.search.includes(q));}if(ev.target.id==='auto-dev-search'){const q=ev.target.value.toLowerCase();document.querySelectorAll('.dev-card').forEach(x=>x.hidden=!x.dataset.search.includes(q));}});document.addEventListener('change',ev=>{if(ev.target.id==='auto-dev-selected')document.querySelectorAll('.dev-card').forEach(x=>x.hidden=ev.target.checked&&!Number(x.dataset.picked));});}
root.AUTOUI={help,view:(tab,s,r)=>({character,skills:skillView,devotions:devotionView,target:targetView,audit,analysis}[tab]||(()=>''))(s,r),preset,install,offline,statName};
})(globalThis);
